### ISSUE TITLE
Google Maps support ?

### ISSUE THREAD

**Issue by ceinmart** [thomaschampagne/stravistix#116]
Hi Thomas , 

How you probably already notice , strava not use google maps anymore.
This is terrible for a lot of users (include me) and all them are complain about this at strava forum . 
Check here : https://strava.zendesk.com/entries/95423147-Feedback-for-Strava-s-new-maps-Open-Street-Maps-

I don't believe strava will back with google maps soon . 
So, can you enable a "patch" to use google maps instead the OSM ??
If you able to do that... you will gain a lot of users... and probably more $$ donators... 

Thank you 
Cesar

**Comment by thomaschampagne** [comment]
@ceinmart Ok, i will handle this feature inside ticket #117 . My bad i created duplicated and referenced duplication issue number in commit. So i will close the ticket. Just follow #117 one.

For the feature itself, it seems i have a good start:

![coeqrewwuaa_trd](https://cloud.githubusercontent.com/assets/151973/9792394/32625768-57e0-11e5-92f7-5643d6e28bcf.png)

**Comment by ceinmart** [comment]
nice!
when you publish this into the plugin , can I disclose this new feature at strava forum? or you prefer not "invade" the strava official support ...

**Comment by thomaschampagne** [comment]
Yes of course ;)
