### ISSUE TITLE
Yearly Progression + Virtual Rides

### ISSUE THREAD

**Issue by ianrollings** [thomaschampagne/stravistix#129]
The yearly progression stats don't match up to the number of km's in my profile.

![screen shot 2015-10-19 at 4 30 07 pm](https://cloud.githubusercontent.com/assets/15190005/10570791/48e7c276-767f-11e5-9c80-33b28faf4106.png)

I think it's got to do with the "Virtual Ride" and the "Stationary trainer" tag as I use Zwift also.

I've done 77.7km in "Virtual Rides" + 13.6km on "Stationary Trainer" which gets closer to the figure, but still not 100% of the way there.

Using the Strava Annual Summary http://www.jonathanokeeffe.com/strava/annualSummary.php and adding my rides + virtual rides, it gives me the same figure as strava, so not sure what is going on here.

Cheers

**Comment by tazmanska** [comment]
@ianrollings There is about 5km's difference. There may be a little difference but this is too big. Only Rides and Runs activities are included in this stats. Could you share a link to your Strava profile page?

**Comment by ianrollings** [comment]
yep, sure can.

https://www.strava.com/athletes/2807503

not sure where the discrepancy is, i cant seem to work it out

**Comment by tazmanska** [comment]
@ianrollings could you send me your annual summary from http://www.jonathanokeeffe.com/strava/annualSummary.php (save as html)?

**Comment by ianrollings** [comment]
@tazmanska sure can

Looks like all the data is in the single html file

[Strava Annual Summary.html.txt](https://github.com/thomaschampagne/stravistix/files/42185/Strava.Annual.Summary.html.txt)

**Comment by ianrollings** [comment]
@tazmanska Just checked out the statistics again and now they are looking correct.

The year progression is now correct for my rides marked as 'ride' but is missing the 'virtual ride' tag. My other 'trainer' rides that are marked as a ride appear in the summary.

Not unhappy with the virtual rides not appearing, but could it be an option to add them into it? or have their own count?

![screen shot 2015-12-01 at 10 12 15 am](https://cloud.githubusercontent.com/assets/15190005/11488120/1bb82c1c-9814-11e5-963d-2eb7cadd2de4.png)
![screen shot 2015-12-01 at 10 12 26 am](https://cloud.githubusercontent.com/assets/15190005/11488130/2b8b9818-9814-11e5-87c6-0cdf83604072.png)
![screen shot 2015-12-01 at 10 11 28 am](https://cloud.githubusercontent.com/assets/15190005/11488137/36130622-9814-11e5-9f8d-bb7221bf081e.png)

**Comment by tazmanska** [comment]
Great! 
There is an issue #159 for the virtual rides option.

**Comment by ianrollings** [comment]
Thanks guys, love the update with the virtual rides checkbox.

Works a treat!

Cheers

**Comment by thomaschampagne** [comment]
You're welcome ;)

Cheers
