### ISSUE TITLE
Pressing multiple times on the current tab adds "View in Google Maps" multiple times.

### ISSUE THREAD

**Issue by MaximeKjaer** [thomaschampagne/stravistix#135]
If I click on "Overview" multiple times, the "View in Google Maps" button is added multiple times, too:

![image](https://cloud.githubusercontent.com/assets/990794/11056657/5e84a7aa-8784-11e5-87f3-96afa9c9a0c1.png)

**Comment by thomaschampagne** [comment]
@MaximeKjaer Thanks for reporting it !
Trying to fix it for next release
Tom

**Comment by thomaschampagne** [comment]
Bug also occurs into running:

ex: https://www.strava.com/activities/406963466/segments
