### ISSUE TITLE
Ascent speed get lower/away from reality after smooth elevation

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#149]
Relating to https://github.com/thomaschampagne/stravistix/pull/147

**Comment by glandais** [comment]
Using https://www.strava.com/activities/436621314

[sample-zwift.xlsx](https://github.com/thomaschampagne/stravistix/files/42766/sample-zwift.xlsx)

For ascent speed, I think it should use :
 - data when speed > treshold
 - grade > treshold

see https://github.com/thomaschampagne/stravistix/pull/150

**Comment by glandais** [comment]
![ascent-zones](https://cloud.githubusercontent.com/assets/864152/11368872/6678578e-92bc-11e5-887f-04b0b89e2d6d.png)
