### ISSUE TITLE
Best splits are not correct

### ISSUE THREAD

**Issue by Langlaeufer** [thomaschampagne/stravistix#152]
at time splits the distance seams to be correct, but the speed is too low.
at distance splits each time is approximately 10 s too short, so the speed is too high (the fastest km is faster than max speed of the whole activity and also faster than fastest minute - which makes no sense.

I found this problem on each activity.
Here the example from above: https://www.strava.com/activities/433205779

**Comment by glandais** [comment]
I'll have a look Thomas

**Comment by tazmanska** [comment]
@Langlaeufer when you hover the coursor over any value, you will see on what exactly split length it was computed. For example (from the activity you pointed) split 1min, distance is 0.75km but it was found on split 1:07. It's because there is no interpolation to divide the activity GPS track to exact 1min segments so the precision depends on GPS log interval.

**Comment by Langlaeufer** [comment]
i noticed, but the correct (because consistent) result would be 
1 km - 1:23 min = 43.4 km/h  (not 1:14 and 49 km/h)
1:02 min - 0.75 km = 43.6 km/h (not 40 km/h)

**Comment by glandais** [comment]
My patch is using a ratio split length/measured length.
Example : 1min split, if you done 1.2km in 1:12, it will display 1km (1.2 * 1:00/1:12)

**Comment by Langlaeufer** [comment]
@glandais This would help. For me it is not clear why the longest distance and the highest speed over 1:00 is based on different segment length (1:07 / 1:03)

**Comment by glandais** [comment]
746.4m is the best value it sees, without looking the duration of it (1:07), with an average of 40.1km/h
703.7m for 1:03 gives an average of 40.21km/h, and it doesn't see any better average.

With my patch, it displays 0.67km, that's the best distance done in 1:00 (based on the 703.7m done in 1:03)

**Comment by Langlaeufer** [comment]
your function said my best 1:03 min was 40 km/h  
at the same time it said my best 1.01 km takes 1:14 min = 49 km/h 
so these 1:14 min are faster (it contains a faster minute). therefore 1:03 for 704 m refers  not to the fastest minute.

**Comment by thomaschampagne** [comment]
@Langlaeufer Will will find here a build with latest patches:

https://dl.dropboxusercontent.com/u/2268286/StravistiX_v2.0.1_Tue_Nov_24_2015_11_58_58%20PM.zip

* Open new tab and type **chrome://extensions** then enter
* Tick **Developer Mode** checkbox
* Click **Load Unpacked Extension** button, then choose **hook/extension/** folder (this is where you have **manifest.json** file)
- Disable official extension from chrome store during testing.

Thanks for all contributing in !

Tom

**Comment by Langlaeufer** [comment]
thanks. I tried. Now It looks as distance, time and speed value of each line is consistent but the main issue is not solved. I may later have a look at the code for myself.

I*m not sure, if you understand what is my point.
The fastest 1 minute has to be faster than the fastest 1 km (in case when speed is less than 60 km/h because than you take more time for 1 km as 1 minute) 

In the example:
The fastest 1 minute should be found at the beginning of the first round. 
The fastest 1 km you found at the correct place, but the time value is too short therefore you calculate a speed higher than maximum speed. (this is clearly not possible)

**Comment by glandais** [comment]
This is very strange, I don't understand why right now.
I tried to add a split of 0.703m, and I get 45s and 55.9km/h!
Can you please provide the GPX?
Issue still open!

**Comment by Langlaeufer** [comment]
@glandais  How can I do this? Im still not familar with github.

**Comment by glandais** [comment]
Drag&drop file in the text area!

Anyway, found the error, time/distance used for splits were just wrong (not same begin and end for both!)

Looking to match your values

**Comment by glandais** [comment]
GPX as txt
[Peiner Triathlon.txt](https://github.com/thomaschampagne/stravistix/files/43543/Peiner.Triathlon.txt)

**Comment by glandais** [comment]
Values computed with #155

![hr3](https://cloud.githubusercontent.com/assets/864152/11390887/6616804e-934e-11e5-97bc-1170ddf0d4dc.png)

**Comment by thomaschampagne** [comment]
Thanks to all !
@Langlaeufer  build here: 

https://dl.dropboxusercontent.com/u/2268286/StravistiX_v2.0.1_Wed_Nov_25_2015_09_36_07.zip

With #155 pull request merged from @glandais 

Thanks !

**Comment by Langlaeufer** [comment]
looks good now

Thomas Champagne <notifications@github.com> schrieb am Mi., 25. Nov. 2015
um 09:39 Uhr:

**Comment by thomaschampagne** [comment]
Fixed in PR #155 via commit https://github.com/glandais/StravaPlus/commit/ee2ccc8799ecb0b1bd00472b010affc466dec02a
