### ISSUE TITLE
Data sampling and statistics

### ISSUE THREAD

**Issue by glandais** [thomaschampagne/stravistix#156]
Currently, samples have all the same weight. If GPS is recording one sample per second, statistics will be time based. If GPS is recording values "smartly", a sample can be very long in distance and/or in time.
If a sample should be ponderated over time elapsed, only samples happening over a predefined speed should be used. This is what is used for distributions.

**Comment by thomaschampagne** [comment]
@glandais Speaking about best splits?

**Comment by glandais** [comment]
yes, and averages/quartiles in activity processor

**Comment by thomaschampagne** [comment]
@tazmanska or @glandais Are you fixing it currently or intend to fix it? If not i will. Just to avoid duplicate work.

Again, thanks for involvement you put in this extension :) 

Tom

**Comment by glandais** [comment]
Done it in best splits, looking in activity processor, I'll commit at the end of lunch break :)

**Comment by glandais** [comment]
Commited weighted percentiles on my branch!
Unable to create a pull request by the way ;(

Inspired from https://en.wikipedia.org/wiki/Weighted_median and https://en.wikipedia.org/wiki/Percentile#Definition_of_the_Weighted_Percentile_method

**Comment by thomaschampagne** [comment]
_Track comment_
Bug fixed via pull request #157 (commit: https://github.com/glandais/StravaPlus/commit/6d130e9f96dc4cba2d2a864d119ecc787ae726b0)

**Comment by thomaschampagne** [comment]
I merged weighted percentiles with your  #157 pull request. Just to resolve some conflicts.

I have strong changes before/after on some activities (ex: https://www.strava.com/activities/432548748).

What's the gain of weighted percentiles in few words? What could you say to a cyclist/runner of 55 years old working in marketing :) ?

Thanks for all again !

**Comment by glandais** [comment]
Weighted percentiles is just like percentiles but using a weight over each sample : time in general, distance for elevation

I'll recheck values used for averages/distribution and may refactor it to get everything the same way

**Comment by thomaschampagne** [comment]
@glandais Thanks, i asked this to you because the documentation about median/quartiles may change

**Comment by glandais** [comment]
No time for it since few days... And it will not be this week end neither :(

**Comment by thomaschampagne** [comment]
@glandais No problem, my question was just answerable by yes or no. In all case i would finish documentation on my side.

Nice weekend to you ;)

Thanks for all !

Tom
