### ISSUE TITLE
Yearly progression bug: wrong counting of activities

### ISSUE THREAD

**Issue by hauke-w** [thomaschampagne/stravistix#166]
I looked deeper in the code to find the cause of the yearly progression bug.
As I assumed [here](https://github.com/thomaschampagne/stravistix/issues/112) the number of activities is wrong (but there is no cap as I first thought).

In AthleteStatsModifier.js, lines 505 and 506, the number of rides and runs are summed up:
`total = parseInt($("div.cycling table tbody:last tr:nth(2) td:last").text() || "0");`
`total = total + parseInt($("div.running table tbody:last tr:last td:last").text() || "0");`

This is not the sum of all activities because there are many other activitiy types! Nevertheless this number ist used to determine how many activity pages should be fetched in line 517:
`for (i = 1, max = Math.ceil(total / 20); i <= max; i++) {`

Example: Currently I have 573 rides, 23 runs and 59 other activities (total: 655). So 30 pages with a total of 600 activities are fetched and 55 activities are ignored, mostly rides.

I am not familar with the Strava/StravistiX code so I cannot fix this bug myself.

**Comment by tazmanska** [comment]
@hauke-w Your are right and the fix is ready to test https://github.com/tazmanska/stravistix/commit/115785b91ba7e21960414f0cbebbf0a270070226

**Comment by thomaschampagne** [comment]
@hauke-w @tazmanska Nice found and work !

**Comment by thomaschampagne** [comment]
@tazmanska Cherry picking your commit https://github.com/tazmanska/stravistix/commit/115785b91ba7e21960414f0cbebbf0a270070226 is sufficient to fix this bug?

Thanks !

Tom

**Comment by tazmanska** [comment]
It should solve the problem. Fix works the way @hauke-w described.

**Comment by thomaschampagne** [comment]
ok thanks ;)
