### ISSUE TITLE
ActivityProcessor SyntaxError

### ISSUE THREAD

**Issue by wcarthur** [thomaschampagne/stravistix#172]
This error hasn't been reported previously AFAIK. 

In Chrome 37.0.2062.120 m, Stravistix 2.2.1:

Uncaught ReferenceError: ActivityProcessor is not defined - Stravistix.js:10
Uncaught SyntaxError: Unexpected identifier - processors/ActivityProcessor.js:210
In the definition of finalizeDistribComputationZones.

**Comment by thomaschampagne** [comment]
Hi,

Thanks for reporting that.

Do you have an activity link where this occurs?

Regards,

Thomas

**Comment by wcarthur** [comment]
See https://www.strava.com/activities/450791645

**Comment by thomaschampagne** [comment]
Hi,

I don't have any issue on this activity, stil the problem exist?

A simple chrome complete restart or unistall/install extension should fix the problem.

Tom

**Comment by thomaschampagne** [comment]
@wcarthur Fixed in 2.2.2

Let me now if problem is fixed for you.

Thomas

**Comment by wcarthur** [comment]
Updated to 2.2.2 and now works in the above version of Chrome. Thanks!

**Comment by thomaschampagne** [comment]
Perfect :)
