### ISSUE TITLE
How you managed to catch the HR values?

### ISSUE THREAD

**Issue by Geovanek** [thomaschampagne/stravistix#178]
I would like to be able to capture the HR values to use my own model zones and TRIMP on my website.
But so far not figured out how.
I use curl php....

This does not return anything for me.

http://www.strava.com/activities/ id_activity /streams?stream_types[]=watts_calc&stream_types[]=watts&stream_types[]=velocity_smooth&stream_types[]=time&stream_types[]=distance&stream_types[]=cadence&stream_types[]=heartrate&stream_types[]=grade_smooth&stream_types[]=altitude&stream_types[]=latlng

**Comment by thomaschampagne** [comment]
@Geovanek It's the good url pattern.

However, you must initiate queries from site itself "strava.com". Use strava API instead in your case.

What do you want to do exactly ? 

**my own model zones?!** you can custom zones in stravistix.

Tom
