### ISSUE TITLE
Cadence issue in segment extended statistics of effort

### ISSUE THREAD

**Issue by motzel** [thomaschampagne/stravistix#181]
![image](https://cloud.githubusercontent.com/assets/1758707/12411210/dd0e5164-be7c-11e5-9b73-a4968decf76e.png)

I think it's stats for four legs ;-) But seriously it seems you don't clear a variable during window init. Every time I open segment stats window it doubles, even for a different segment.

![image](https://cloud.githubusercontent.com/assets/1758707/12411243/421c552e-be7d-11e5-9b8c-a55e723db304.png)

**Comment by thomaschampagne** [comment]
@motzel Could you give me the activity id where you have this problem?

**Comment by thomaschampagne** [comment]
@motzel Oups closed/open ticket by mistake...
Could you give me the activity id where you have this problem? I will fix that for next release

**Comment by motzel** [comment]
https://www.strava.com/activities/473266494/segments/11362683767

**Comment by thomaschampagne** [comment]
@motzel I'm not able to reproduce your problem onto your activity. i'm not able to "double" your cadence each time i click on extendend stats button of effort

Do you still the problem?

What i get and continuously get...
![image](https://cloud.githubusercontent.com/assets/151973/12705086/3252c24e-c86a-11e5-9eb2-24e366e31e19.png)

**Comment by motzel** [comment]
Yes, I'm still experiencing this. It affects every single running activity with segments, main or others. Values are correct when I open extended stats window first time and are doubled for the second and subsequent openings. Whole story starts again after page reloading. 

Maybe one of installed extensions causing this behaviour, I'll try to isolate this issue by creating new empty Chrome profile and installing them one by one.

**Comment by motzel** [comment]
I've created a new profile and at the beginning it seemed that the problem no longer exists, but when I've enabled "Enable both legs extended cadence data" option in Stravistix settings, I've experienced it again. So it seems that a bug is closely associated with this option.
