### ISSUE TITLE
VAM Mismatch between strava and plugin on segment efforts

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#184]
From Allan Ruyters <allan.ruyters@gmail.com>

VAM (Vm/hr) stats are totally different from Strava.  Screenshot from a recent ride for the same segment.  Strava VAM first, then Stravistix VAM.  Why do they differ so much?  
This is not isolated, VAM numbers are much higher on all segments, from Stravistix, vs Strava.

Id: https://www.strava.com/activities/473467654

----
Also reported by: Antti Rasinen <ars@iki.fi>

>I installed Stravistix and checked out my statistics on a long bike ride I did last summer. To my surprise, the plugin reported my average VAM as nearly 1600 m/h… which sounds way way way too high.
The activity is at https://www.strava.com/activities/328700911 if you want to see what goes wrong. I can also provide a GPX dump if necessary.
…

**Segment efforts test samples:**

Compare **Strava VAM value** with **avg ascent speed from plugin** -> Make them match :)

- [ ] https://www.strava.com/activities/473467654/segments/11367189001
- [ ] https://www.strava.com/activities/187311473/segments/4385440906
- [ ] https://www.strava.com/activities/187311473/segments/4385441236
- [ ] https://www.strava.com/activities/343080886/segments/8147784775
- [ ] https://www.strava.com/activities/208748758/segments/7153239651
- [ ] https://www.strava.com/activities/482167925/segments/11569886558
- [ ] https://www.strava.com/activities/482167925/segments/11569886558
- [ ] https://www.strava.com/activities/482830818/segments/11586493730

**Comment by thomaschampagne** [comment]
Check VAM for:

https://www.strava.com/activities/473467654/segments/11367189001

**Comment by glandais** [comment]
well done!

**Comment by thomaschampagne** [comment]
@glandais After three tries of fixing (branches issue/184, issue/184-2 and issue/184-3) and perseverance... I didn't find the right computation to get consistent Ascent Speed results on segment efforts stats.

So i disabled Ascent Speed panel on segment efforts stats. Not a true fix :/
