### ISSUE TITLE
Current year prevision target on year progression

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#195]
**Idea from: @matt39**

>In the year progression chart would be nice and helpful to have the "current year prevision" based on the target setted.
![unnamed](https://cloud.githubusercontent.com/assets/151973/13004672/152462f6-d17d-11e5-8e89-b71013b98e43.png)

**Comment by ianrollings** [comment]
I was just about to submit a feature request for that, I think it would be amazing!

**Comment by thomaschampagne** [comment]
Yes not so hard to do.

I'm on other big features currently. Please wait.

;)

**Comment by praveentiru** [comment]
A slightly different implementation of this enhancement but, it works with minimal code changes. To capture target and plot progression, I have created an additional member in data array with index being one year into future. :)

I have implemented for distance and distance in last 30d. I am not able to understand what distance last year stands for so, will implement if I understand what it represents. Screen grabs below.

Distance
![distance_trend](https://cloud.githubusercontent.com/assets/12044936/15562746/a871f26e-231f-11e6-8a6e-f9f79c4ff737.PNG)

Distance in last 30d
![distance_30d](https://cloud.githubusercontent.com/assets/12044936/15562766/c775cbfe-231f-11e6-836d-5fda4cee5f38.PNG)

I have to create proper mock data to test this. As my account data is minimal at present.

**Comment by praveentiru** [comment]
Added support for tracking time target as well.

Tested with all feasible cases:
* No target
* User preference in miles
* User preference in km
* Time target
* Change of datatype
* Un-check Target line to hide the target

Let me know if you see any possible concerns.
