### ISSUE TITLE
What's the boundary for Hilly grade profiles ?

### ISSUE THREAD

**Issue by philipwhiuk** [thomaschampagne/stravistix#196]
I feel like calling both this: https://www.strava.com/activities/490658298/overview# (less than 100 feet max change between high and low over 11 miles) and this: https://www.strava.com/activities/487660682# (1000 ft, several times, marathon distance) hilly in the extended statistics grade profile is odd.

Is it a Strava definition?

**Comment by thomaschampagne** [comment]
@philipwhiuk Thanks for reporting this.
No it's not a stava definition. It's a plugin definition.

Basically if you have more then 60% of time on flat it's FLAT else it's
HILLY.

Take a look @
https://github.com/thomaschampagne/stravistix/blob/develop/hook/extension/js/processors/ActivityProcessor.js#L732

Does this help you?

Tell me is it's still a bug for you. Else juste close ticket (if you have
rights). I can also close it.

Cheers,

Tom


On Fri, Feb 12, 2016 at 1:02 PM Philip <notifications@github.com> wrote:

> I feel like calling both this:
> https://www.strava.com/activities/490658298/overview# (less than 100 feet
> max change between high and low over 11 miles) and this:
> https://www.strava.com/activities/487660682# (1000 ft, several times,
> marathon distance) hilly in the extended statistics grade profile is odd.
>
> Is it a Strava definition?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thomaschampagne/stravistix/issues/196>.
>
-- 
Thomas Champagne
