### ISSUE TITLE
Version 3.2 Wrong climbing pace running

### ISSUE THREAD

**Issue by Langlaeufer** [thomaschampagne/stravistix#201]
Wrong climbing pace in activity overview!
In extended stats it looks correct.

Examples:
https://www.strava.com/activities/482321884
https://www.strava.com/activities/481117111
00:08 /km Avg climbing pace

**Comment by thomaschampagne** [comment]
Indeed, there is a problem here.

i have same problem here https://www.strava.com/activities/393116784

I will push an hotfix.

Thanks for reporting that

On Wed, Mar 9, 2016 at 10:26 AM, Langlaeufer <notifications@github.com>
wrote:

> https://www.strava.com/activities/482321884
> https://www.strava.com/activities/481117111
> 00:08 /km Avg climbing pace (are this h:min ?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thomaschampagne/stravistix/issues/201>.
>



-- 
Thomas Champagne - http://thomaschampagne.github.io

**Comment by Langlaeufer** [comment]
Now climbing pace is also wrong in extendet statistic!
