### ISSUE TITLE
Version 3.2 Hide activities under distance.

### ISSUE THREAD

**Issue by Langlaeufer** [thomaschampagne/stravistix#202]
Filter seems not to work. I tried it with different settings:

Example:
My filter setting for testing 100 km biking, 10 km for running:

On my dashbord:
4.4 km running
25 km riding
36 km riding
6 km running
...
(from starred athlets)

**Comment by thomaschampagne** [comment]
Looking in dashboard feed? after page reload? Which language do you use in
strava?

On Wed, Mar 9, 2016 at 10:33 AM, Langlaeufer <notifications@github.com>
wrote:

> Filter does not work.
>
> My filter setting for testing 100 km biking, 10 km for biking:
>
> On my dashbord:
> 4.4 km running
> 25 km riding
> 36 km riding
> 6 km running
> ...
> (from starred athlets)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thomaschampagne/stravistix/issues/202>.
>



-- 
Thomas Champagne - http://thomaschampagne.github.io

**Comment by Langlaeufer** [comment]
yes dashbord feed after reload/restart
Language DE-DE

**Comment by thomaschampagne** [comment]
@Langlaeufer Thanks ! 

I got the problem. It's related to the language: deutsch.

If you witch to English temporally this will work.

I will hotfix this with the other bug you tracked.

A version 3.2.1 will be release asap !

Thanks for reporting !

Tom

**Comment by Langlaeufer** [comment]
Thanks for the fast fix.

But but it still does not work when Strava Enhancement Suite is activated. 
Also grouped activities are not hidden, but this perhaps is a feature?

**Comment by thomaschampagne** [comment]
It not a feature, it's a miss :)

What happend when you disable Strava Enhancement Suite? from
"chrome://extensions/" Tab.

Nothing to deal with... What would you like to see from "Strava Enhancement
Suite" inside Stravistix?

Cheers

Tom

On Wed, Mar 9, 2016 at 10:16 PM Frank <notifications@github.com> wrote:

> Thanks for the fast fix.
>
> But but it still does not work when Strava Enhancement Suite is activated.
> Also grouped activities are not hidden, but this perhaps is a feature?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thomaschampagne/stravistix/issues/202#issuecomment-194510057>
> .
>
-- 
Thomas Champagne

**Comment by Langlaeufer** [comment]
> What happend when you disable Strava Enhancement Suite? from
"chrome://extensions/" Tab.

Without Strava Enhancement Suite your filter works fine. 

> Nothing to deal with... What would you like to see from "Strava Enhancement
Suite" inside Stravistix?

For me Repeated Segments Statistik is more interesting than filtering the dashboard stream
