### ISSUE TITLE
HR percentage info in other athlete's activities

### ISSUE THREAD

**Issue by sashock** [thomaschampagne/stravistix#203]
I'm not sure but I think the HR percentage information on someone else's is irrelevant since it's probably based on the HR zones one defines for himself in stravistiX settings.

**Comment by philipwhiuk** [comment]
It does warn you about this. I think it's slightly interesting to see what equivalent zones they are working at. But it is misleading and doesn't add much.

**Comment by thomaschampagne** [comment]
So removing it or not?

**Comment by sashock** [comment]
I'd go with removing :)
