### ISSUE TITLE
3.2.1 Climbing pace (running) gets wrong after reload

### ISSUE THREAD

**Issue by Langlaeufer** [thomaschampagne/stravistix#205]
Very strange behavior. When I open a activity the first time, everything is o.k. but after a reload the climbing pace gets wrong in extended statistics and in the activity summary. For example:

https://www.strava.com/activities/482321884 (climbing pace 00:07/km)

![climbingpace](https://cloud.githubusercontent.com/assets/15994341/13666013/91f048b2-e6af-11e5-820c-49f8486e6f9a.png)

After deleting the browser data (google chrome) I get the correct pace back for the first load.

os: windows 7
language: German

**Comment by thomaschampagne** [comment]
Thanks for reporting it !

I released a new hotfix.... Without integrate a new error ;)

On Thu, Mar 10, 2016 at 11:05 AM, Frank <notifications@github.com> wrote:

> https://www.strava.com/activities/482321884 (climbing pace 00:07/km)
> At this activity climbing pace is wrong in at summary an in extended
> statistic!
>
> [image: climbingpace]
> <https://cloud.githubusercontent.com/assets/15994341/13666013/91f048b2-e6af-11e5-820c-49f8486e6f9a.png>
>
> In other cases it looks ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thomaschampagne/stravistix/issues/205>.
>



-- 
Thomas Champagne - http://thomaschampagne.github.io
