### ISSUE TITLE
Unable to view 'Distance last year'

### ISSUE THREAD

**Issue by philipwhiuk** [thomaschampagne/stravistix#219]
Version: StravistiX for Strava 3.4.0 Stable

The graph doesn't change and errors are logged in the Chrome console

```
Uncaught TypeError: Cannot read property 'values' of undefined
processData @ AthleteStatsModifier.js:654
(anonymous function) @ AthleteStatsModifier.js:803
Z.event.dispatch @ strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:25
m.handle @ strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24
```

```
Uncaught TypeError: Cannot read property 'text' of undefined
(anonymous function) @ AthleteStatsModifier.js:851
handleMouseOverGraph @ AthleteStatsModifier.js:849
(anonymous function) @ AthleteStatsModifier.js:864
Z.event.dispatch @ strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:25
m.handle @ strava-head-15cde5e942e3bd5032a3d6e12d12fe5c.js:24
```

when selecting 'Distance last year' in the chart view for 'My year progressions to current month/day' for either cycling or running

**Comment by damian-pastorini** [comment]
The problem started after the last strava page update.
It seems they changed the layout in the profile section.

**Comment by thomaschampagne** [comment]
@philipwhiuk @damian-pastorini This should be fixed in latest 3.5.1 version.

Do you confirm? If yes you can close this ticket ;)

Tom

**Comment by philipwhiuk** [comment]
Nope it's still broken in 3.5.1 Stable:

```
AthleteStatsModifier.js:654 
Uncaught TypeError: Cannot read property 'values' of undefined
processData @ AthleteStatsModifier.js:654
(anonymous function) @ AthleteStatsModifier.js:803
Z.event.dispatch @ strava-head-15cde5e….js:25
m.handle @ strava-head-15cde5e….js:24
```

**Comment by philipwhiuk** [comment]
Okay, I did some debugging on my data to work out why.

I have gaps in my data. For example, in running I have no data for 2009-2013. In cycling I have no cycling for this current year.

So these gaps are causing it to break. There's no data[2009] so it when it does data[activity.y + 1] with activity.y == 2008, it breaks.

**Comment by philipwhiuk** [comment]
Thanks  @praveentiru and @thomaschampagne - it works fine now in 3.6.0. Much appreciated :)
