### ISSUE TITLE
WindyTy fancybox weather maps initialise with no map

### ISSUE THREAD

**Issue by SparkyT** [thomaschampagne/stravistix#227]
WindyTyModifier.js line 134, showWeather function sets the zoom level for the embedded weather map to be 20 which is higher than the maximum windyty allows so no map shows until the user zooms out.  Looking at https://embed.windyty.com/embedmake.html , the highest zoom level is now 11.

**Comment by thomaschampagne** [comment]
@SparkyT Thanks for report ! Now fixed. It will be brought in next release
