### ISSUE TITLE
Weighted power computation erroneous?

### ISSUE THREAD

**Issue by hauke-w** [thomaschampagne/stravistix#229]
I think the weighted power displayed in the Power section of the extended statistics is wrong. It seems to be much too high.

For example, for my latest ride with 246W average and 15.7% at 0 to 5 W Stravistix displays 353W weighted power. Strava's own computation and Golden Cheetah (XPower) show more realistic 275W, Garmin says 293W normalized power. I am aware there are various models for computing weighted power but Stravistix' current computation (I remember it used to be correct) seems not to conform with any of these.
![stravistix power](https://cloud.githubusercontent.com/assets/9463839/15287291/26d35f00-1b62-11e6-8f62-4cd240e5e680.PNG)

**Comment by thomaschampagne** [comment]
@hauke-w what is the activity id?

FIY formula used is: https://raw.githubusercontent.com/thomaschampagne/stravistix/develop/hook/extension/options/app/img/np_equation.png

It's computed only while moving.

Code where it's implemented is here : https://github.com/thomaschampagne/stravistix/blob/develop/hook/extension/js/processors/workers/ComputeAnalysisWorker.js#L423

**Comment by hauke-w** [comment]
Here is the activity I mentioned above: https://www.strava.com/activities/576828592

Here is another example (20 second sprints) where the weighted power seems wrong (305 W ): https://www.strava.com/activities/580204083

**Comment by hauke-w** [comment]
I found a post by A. Coggan where he said a rolling 30 second average should be computed in the first step. You don't compute a 30s average do you? That could explain why I observe this for activities with many short power peaks, only.

> 1) starting at the 30 s mark, calculate a rolling 30 s average (of the preceeding time points, obviously). 
> 2) raise all the values obtained in step #1 to the 4th power. 
> 3) take the average of all of the values obtained in step #2. 
> 4) take the 4th root of the value obtained in step #3. 

Source: http://forum.slowtwitch.com/Slowtwitch_Forums_C1/Triathlon_Forum_F1/Normalized_Power_Formula_or_Calculator..._P3097774/

**Comment by thomaschampagne** [comment]
No i am not getting avg each 30s "window" ypu may found the gem to résolve this bug... lot of people raise me strange resuts on...

I Will try this méthode..not hard..

* Do you have power meter ?

* Do you have other activities with wrong and expected result?


I Will push dev builds in that ticket 


Tom

**Comment by thomaschampagne** [comment]
@hauke-w 

I developed the 30s windows you provided through Andy cogan forum post. It seems more accurate. I looked your account and some pro account (which have power sensor for sure). It make more sense now for, cyclist without power meter. (weighted power from estimated values).

The improvement at been introduced via commit https://github.com/thomaschampagne/stravistix/commit/2433488acd156c4d3ed226534cc850e4e4d7f36f .

You can test the associated build with that commit here: http://champagne.thomas.free.fr/stravistix/builds/origin/develop/stravistix_b9_commit-2433488acd156c4d3ed226534cc850e4e4d7f36f.zip

I can still use weighted power computed by strava if user has power sensor... This implies plugin don't compute anymore this stats for cyclist with power meter.

Let me know if we close or not yet this ticket, what we do... etc ... ;)

Tom

**Comment by hauke-w** [comment]
I cannot download that build: 'Erreur 500 - Erreur interne du serveur'.

**Comment by hauke-w** [comment]
I have tested that build and looked at some of my acivities including the ones that I mentioned above. Now, weighted power is plausible. It is almost identical with normalized power displayed in Garmin Connect. Stravistix' value is at maximum 2 Watts less. I use a power meter.

I believe this issue is now fixed and the ticket can be closed.
