### ISSUE TITLE
Click on total time or elevation summary in sidebar lead to collapse whole block.

### ISSUE THREAD

**Issue by ilyaguy** [thomaschampagne/stravistix#230]

**Comment by thomaschampagne** [comment]
@ilyaguy Could provide screenshot or more detail ?

**Comment by ilyaguy** [comment]
Click on highlighted items
![image](https://cloud.githubusercontent.com/assets/6704355/15321893/17b95f84-1c42-11e6-9eee-81fe2cb7ba89.png)

Result:
![image](https://cloud.githubusercontent.com/assets/6704355/15321937/4e7b3678-1c42-11e6-9e71-79e188a27c09.png)

**Comment by thomaschampagne** [comment]
Unable to reproduce it. Did you do specific steps?

**Comment by ilyaguy** [comment]
No, I don't have specific steps.

As I see `n.prototype.switchTab = function(t) {` bound to all `li` in this section, but those items are not tab switches.

**Comment by thomaschampagne** [comment]
@ilyaguy Do you still experience the problem?

(I'am still not able to got the bug with several various account and chrome instance)

**Comment by hauke-w** [comment]
I can reproduce it with Opera 37.0

**Comment by thomaschampagne** [comment]
@hauke-w It's a not a stravistix bug :). (i didn't understood well your actions).

I'm able to reproduce now the problem with the plugin activated. Chrome, Canary, Opera, Vivalidi. Even firefox where extension doesn't exist at the moment...
