### ISSUE TITLE
"Last 30 days" doesn't include activities from the day in question

### ISSUE THREAD

**Issue by graeme0811** [thomaschampagne/stravistix#232]
On the graph of total distance for the last 30 rolling days, the activities used to calculate the sum do not include the day they are being calculated for.
This is most noticeable on the last data point (today), as any activities recorded for today are not included in the sum.

The reason for this is that time used in the calculation is essentially 0 milliseconds into the day, and not the end of the day (Lines 657 - 667 in AthleteStatsModifier.js)

Please let me know if more explanation is required.

**Comment by graeme0811** [comment]
PR created with suggested fix: https://github.com/thomaschampagne/stravistix/pull/233

**Comment by thomaschampagne** [comment]
Fixed by @graeme0811 through #233 PR
