### ISSUE TITLE
Duplication of on Click handler in AthleteStatsModifier.js

### ISSUE THREAD

**Issue by praveentiru** [thomaschampagne/stravistix#234]
This commit linked at bottom has created two duplicate click handlers for Chart creation in athlete stats in profile page. I have attached the two click handlers created after the merge as [Click_Handler_1.txt (Line:206-513)](https://github.com/thomaschampagne/stravistix/files/282149/Click_Handler_1.txt) and [Click_Handler_2.txt (Line:515-822)](https://github.com/thomaschampagne/stravistix/files/282151/Click_Handler_2.txt). (File after merge: [here](https://github.com/thomaschampagne/stravistix/blob/c96a91669b60ee88647dadae08785b34ba44c229/hook/extension/js/modifiers/AthleteStatsModifier.js))

Moreover, it seems that all the new development like Distance in last 30d has happened in the second click handler. I have performed the diff and the only difference between the code is addition of new checkboxes and whitespaces. [Current File on Develop Branch](https://github.com/thomaschampagne/stravistix/blob/develop/hook/extension/js/modifiers/AthleteStatsModifier.js). I have also attached extract of the current handler in [Click_Handler_Develop.txt (Line: 206-515)](https://github.com/thomaschampagne/stravistix/files/282150/Click_Handler_Develop.txt).

I believe we can remove all the code from Line: 206-515 safely without any side effects. I will submit the pull request for the same soon. Please review and comment

Reference: [Commit](https://github.com/thomaschampagne/stravistix/commit/c96a91669b60ee88647dadae08785b34ba44c229#diff-4695fdf96e55318a0f50bb04c86c8ed5)

**Comment by thomaschampagne** [comment]
@praveentiru thanks

**Comment by praveentiru** [comment]
I have spent whole day to understand the difference between two methods. So, no problem it is actually for me. :)

I have submitted the pull request for same.

**Comment by praveentiru** [comment]
Fix merged. Closing issue.
