### ISSUE TITLE
Potential Gulp Watch slowdown  due to inclusion of node_modules

### ISSUE THREAD

**Issue by praveentiru** [thomaschampagne/stravistix#241]
Currently, gulp watch includes the entire extension directory including node_modules which will potentially slow down watch significantly if large npm module which is not completely used into pre-req.

Example: [CLDR-Data-NPM](https://github.com/rxaviers/cldr-data-npm). To support translation, it provides lot of data but, it needs to be used selectively based on actual need.

Current code:
<code>gulp.watch('hook/extension/\*\*/\*', ['cleanDistSrcOnly', 'build']);</code>

Proposed Patch:
<code>    gulp.watch([
        'hook/extension/config/\*',
        'hook/extension/css/\*',
        'hook/extension/icons/\*',
        'hook/extension/js/\*\*/\*',
        'hook/extension/locales/\*',
        'hook/extension/options/\*\*/\*',
        ], ['cleanDistSrcOnly', 'build']);
</code>

This removes watch of node_modules. Please comment

**Comment by thomaschampagne** [comment]
Yes indeed. i will improve that

**Comment by praveentiru** [comment]
Had the patch ready. Pushed the same for merge.
