### ISSUE TITLE
Request: Add speed based on Elapsed time

### ISSUE THREAD

**Issue by tariquesani** [thomaschampagne/stravistix#252]
It would be great help to Brevet / Audax or any long distance riders if the speed based on Elapsed time can be shown as well. It is a simple calculation but my JS skill do not extend far enough to do the modification and create a Pull Request.

Thanks
![yay gran fondo done ride strava](https://cloud.githubusercontent.com/assets/27067/15845283/2bcfd2d4-2c8f-11e6-93b1-4ede18d9f880.png)

**Comment by tariquesani** [comment]
And since I am impatient I whipped up a quick and _very dirty_ extension for the time being at 

https://github.com/tariquesani/strava-total-speed

**Comment by thomaschampagne** [comment]
@tariquesani Easy JS for me :) . Good Idea !

Do you have some "marketing" terms to promote this? "Your avg speed with beers pauses" ?! ... Which signifiant name could you give to this field?

Release in 3.9.0 probably

Just a through.... It's kind linked to "move ratio"

Tom

**Comment by tariquesani** [comment]
We simply call it Total Speed locally. That was the term used in one of the threads in Strava forum as well. Yes, it is kind of related to move ratio.  

Watching the repo. Keen to understand where the various parts of fit into this extension.

**Comment by glandais** [comment]
In french we are used to say "vitesse commerciale" for trains. But I've not fund anything similar in english...

**Comment by thomaschampagne** [comment]
@glandais well seen la "vitesse commerciale"

What about "Rest speed" ?

**Comment by tariquesani** [comment]
Thank you very much!
