### ISSUE TITLE
Not Seeing Stravistix Stats on Trainer Rides

### ISSUE THREAD

**Issue by malarickk** [thomaschampagne/stravistix#273]
Using 810 to record from P2M while doing TrainerRoad workouts on my Kickr. When I upload to Strava don't get any Stravistix stats. Works fine if I push the data from the TrainerRoad site but prefer to use 810 data as my P2M and Kickr don't match up perfectly wattage-wise and I trust my P2M more. Might this have something to do with GPS being off during recording and/or no speed data? 

Here's an example: https://www.strava.com/activities/712527375

Thanks!

**Comment by thomaschampagne** [comment]
Hi got the problem.

You are not seeing rides since there is no speed data to your ride. Indeed i need velocity data for some stats in graph, 

I will see to support trainer which don't push velocity data.

**Comment by malarickk** [comment]
Yes, what I upload is just the power/cadence/hr data that is recording on
my 810, so no speed sensor involved. Don't want to inflate my mileage with
trainer miles :)
Thanks so much!
Keith

**Comment by thomaschampagne** [comment]
Fixed for next release

**Comment by malarickk** [comment]
Thank you!
