### ISSUE TITLE
Not syncing a 2nd activity

### ISSUE THREAD

**Issue by R0b1et** [thomaschampagne/stravistix#313]
**Bug description:** I did a sync earlier in the day, after I went ice skating with my kids... which I saved on strava more because I saw you could! - and I'd been intrigued to see my HR while doing so scateing teaching. Then went on Zwift for 90 minutes (132 - TRIMP) which the sync isn't catching. 

**Actual Behavior:** a manual resync produces: "Sync done." - but the (much more TRIMP) isn't being included

**Expected Behavior: ** the resync to catch and represent this new activity

**Steps to Reproduce:** 
- ... do an activity (maybe it has to be an ice skate?)
 - ...sync your activities
 - ...do another and attempt to sync again.

**Chrome version** Version 54.0.2840.99 m

**Plugin version:** StravistiX for Strava 5.0.2

**Activities links?:** 
Skate: https://www.strava.com/activities/798782833
Virtual Ride: https://www.strava.com/activities/798941270

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
StravistiX.js:85 Skip handlePluginInstallOrUpgrade since we are on a sync
d3nn82uaxijpm6.cloudfront.net/assets/strava/feed/manifest-d9b50e4e26912c61cb8a693a79de40c1.js:76 Uncaught TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'.(…)
StravistiX.js:693 A previous sync exists on Sat Dec 10 2016 22:50:42 GMT+0000 (GMT Standard Time)

Hope that helps, great extension and fabulous feature.
Rob

**Comment by thomaschampagne** [comment]
A 5.1.0 will be released on sunday. It should fix some sync issue like yours. Keep me updated after update ;)

**Comment by R0b1et** [comment]
Wow, that was quick. I guessed I couldn't be alone... unless it was an ice
skate - virtual ride special, when I might be pretty unique.

Ta.

On Sat, Dec 10, 2016 at 11:01 PM, Thomas Champagne <notifications@github.com

**Comment by thomaschampagne** [comment]
It's in the process of Alpha versions ;) Bugs and fixes ;) Beta for christmas ;)

**Comment by R0b1et** [comment]
been there. That's why I was trying to be as specific as I could be...
incase what the activities were mattered.

Rob

On Sat, Dec 10, 2016 at 11:06 PM, Thomas Champagne <notifications@github.com

**Comment by thomaschampagne** [comment]
Fixed
