### ISSUE TITLE
Incorrect year shown in goals sidebar

### ISSUE THREAD

**Issue by stiplady** [thomaschampagne/stravistix#317]
**Bug description:** 
Goals section on profile shows 2016 instead of current year, possibly hardcoded?

**Actual Behavior:** 
Shows 2016

**Expected Behavior:** 
Should show 2017 (or current year)

**Steps to Reproduce:** 
Visible on the athlete profile page

**Chrome version** 
55.0.2883.95 

**Plugin version:** 
5.2.0

**Activities links?:** 
n/a

**Console errors? (press F12 to see developer console, and copy paste here):** 
No errors, just standard console logging reporting successful actions

**Link screenshots or youtube video link if necessary:**
![screenshot 2017-01-09 12 06 16](https://cloud.githubusercontent.com/assets/1472292/21766123/7432def2-d664-11e6-9949-e323504515d4.png)

**Comment by damian-pastorini** [comment]
:+1: also, the month info is wrong:
![image](https://cloud.githubusercontent.com/assets/1211779/21896822/69cb52b4-d8c6-11e6-9e49-05003380a92d.png)

**Comment by stiplady** [comment]
Strange, my year and month shows the same / correct number of miles travelled
![screenshot 2017-01-12 15 59 51](https://cloud.githubusercontent.com/assets/1472292/21897037/50c1b5b4-d8e0-11e6-94b5-b234d18d0bd3.png)

**Comment by thomaschampagne** [comment]
Linked to #320

**Comment by stiplady** [comment]
@thomaschampagne I'm happy to try and take a look at this and possibly the other connected tasks if you'd like me to?

**Comment by thomaschampagne** [comment]
Comment message to also link https://github.com/thomaschampagne/stravistix/issues/306
