### ISSUE TITLE
No calculation on training with only powermeter

### ISSUE THREAD

**Issue by pochitalin** [thomaschampagne/stravistix#318]
Stravistix do not calculate in "Multisports Fitness Trend" sessions where is only powermeter (without speed and heartrate). Also when calculating stress points if there is heartrate and power a priority should be on power, not on heartrate.

Here is my training https://www.strava.com/activities/826285113

**Comment by thomaschampagne** [comment]
Planned still beta ;)

**Comment by thomaschampagne** [comment]
WIP. Released in 5.4.0.
