### ISSUE TITLE
"This week" bar breaks layout.

### ISSUE THREAD

**Issue by hamburger1984** [thomaschampagne/stravistix#320]
**Bug description:** 
Riding more than expected for this week, the bar gets too wide.

**Actual Behavior:** 
"This week" bar to wide.

**Expected Behavior:** 
"This week" bar stays inside the box, but "Today" label & marker moves to an appropiate location.

**Steps to Reproduce:** 
- Get ahead of pace for "this week".
- Observe "this week" bar.

**Chrome version** 
55.0.2883.87

**Plugin version:** 
5.3.0

**Activities links?:** 
none.

**Console errors? (press F12 to see developer console, and copy paste here):** 
none.

**Link screenshots or youtube video link if necessary:**
![screenshot](https://cloud.githubusercontent.com/assets/438976/21962303/d3a0b392-db22-11e6-86c9-5ce30cce9b10.png)

**Comment by thomaschampagne** [comment]
I will disable this feature on next release. Too much problems at the moment.

It should come back in the new UI (Dashboard & target section).

Thomas

**Comment by hamburger1984** [comment]
Sorry to hear, you're going to disable this. But as I understand it's going to come back so that's good.

Thanks for looking into this issue.
