### ISSUE TITLE
Multi activities in multisports fitness trend

### ISSUE THREAD

**Issue by geppoluc** [thomaschampagne/stravistix#329]
**Bug description:**  I noticed that the multisport fitness trend only considerds one activity per day even in case more than one activity is available. For example, today I did one cycling activity outdoor (only hr data available) and a shor activity on a trainer indoor (hr and powermeter data available). The TRIMP is the result of only one activity, in my case the shortest one, i.e. the indoor one.

**Actual Behavior: Only one activity is considered by Stravistix** 

**Expected Behavior: The multisport fitness trend should consider the two activities in the assesment of the TRIMP, PSS, Fitness and Fatigue, as other software are correctly doing (for instance Golden Cheetah)**

**Comment by thomaschampagne** [comment]
@geppoluc Could provide me a backup of your history to debug?

Thanks

**Comment by geppoluc** [comment]
Hi Thomas,
attached please find the backup of my history.

The two activities are:
https://www.strava.com/activities/848672764   (hr and powermeter data)
https://www.strava.com/activities/848157602   (only hr data, this activity 
is not considered in the calculation of fitness, fatigue and form)

I also tried to delete from Strava the first activity (the one with hr and 
power data) and only then the multisport fitness trend was considering the 
other activity

Let me know if you need any additional detail
Cheers and thanks for your nice addon,
Luca

**Comment by thomaschampagne** [comment]
@geppoluc Your  problem should be fixed :)

Here is a build from CI if you want to test and confirm the fix:
https://ci.appveyor.com/project/thomaschampagne/stravistix/branch/develop/artifacts

Thx ;)

Tom

**Comment by thomaschampagne** [comment]
Mistake from me... should not be fixed finally. I missed something

**Comment by thomaschampagne** [comment]
@geppoluc fixed for sure yersterday evening.

Get test build here: https://ci.appveyor.com/project/thomaschampagne/stravistix/branch/develop/artifacts
Install steps: https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

Tom

**Comment by geppoluc** [comment]
It looks to be working. I saw you introduced the “Total Stress”. 

I am not sure the PSS should be simply summed to the TRIMP, this is something you may know.

 

What I know is that other software that I am using do not do it. They simply consider either the TRIMP or a stress score assessed relying on the powermeter data. And they do it without mixing the two components which is something extremely interesting for multisport/ multi-bike training.

 

Thanks,

Luca

 

 

 

Da: Thomas Champagne [mailto:notifications@github.com] 
Inviato: 31 January 2017 09:43
A: thomaschampagne/stravistix
Cc: geppoluc; Mention
Oggetto: Re: [thomaschampagne/stravistix] Multi activities in multisports fitness trend (#329)

 

@geppoluc <https://github.com/geppoluc>  fixed for sure yersterday evening.

Get test build here: https://ci.appveyor.com/project/thomaschampagne/stravistix/branch/develop/artifacts
Install steps: https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

Tom

**Comment by thomaschampagne** [comment]
I'm not mixing PSS and TRIMP for a same activity.

I sum X stress scores for X activities of a day.

X can be PSS (if available) even if you have TRIMP available for the same activity. Else X is TRIMP

**Comment by geppoluc** [comment]
I see.

I'm not an expert and just new to these topics, but I noticed that for most 
of my activities (for which hr and power data are concurrently available) 
the TRIMP score is nearly the double of the PSS score. For instance in this 
activity (https://www.strava.com/activities/845319807) the TRIMP is 90 and 
PSS 45.

I do not know if there is anything (which you probably know) in the 
scientific literature related to the aggregation of the two scores (PSS and 
TRIMP). In case there is not it would be an interesting topic to be 
investigated.

As a preliminary (and brutal) attempt, for each athlete, I would define a 
"substitution rate" based on the scores of old activities:

K=average(TRIMP_old/PSS_old)   In my case it would be K~=2

K could be used for the estimation of the Total Stress in case hr/power data 
is missing.

But maybe I am completely wrong.

Cheers,
Luca

**Comment by thomaschampagne** [comment]
Hi luca,

Does your ftp well entered in stravistix? I'm expreriencing same thing on strava fitness graph when use Trimp + PSS.

I also have same diff than you

PSS formula i use: https://github.com/thomaschampagne/stravistix/blob/develop/plugin/options/app/services/FitnessDataService.ts#L111

Which value other software (which one?) are giving you for 29/01 ?

(can't open your private? activity)

Tom

**Comment by geppoluc** [comment]
Hi Tom,

 

I checked my settings in Stravistix (FTP = 266 W (estimated from CP20 = 280 W), Max hr = 181, rest hr = 52). To define them I took a 20’ test with a personal trainer, which means that I am quite confident about these values.

 

I use Golden Cheetah (http://www.goldencheetah.org/), which you probably know and I find to be really complete, maybe too complex for an average (Strava) user. For that same activity (26/1) it gives me TRIMP = 87 (instead of 90 by Stravistix) and TriScore = 48 (instead of PSS = 49 by Stravistix). The two scores are reasonably close to think the difference could be a matter of rounding or normalization. I modified the privacy of the activity (https://www.strava.com/activities/845319807/overview).

 

What I was noticing is that Golden Cheetah produces two different “Training Stress Balance” charts: (1) for the TRIMP and (2) for the TriScore. 

 

Cheers,

Luca

 

 

Da: Thomas Champagne [mailto:notifications@github.com] 
Inviato: 01 February 2017 09:06
A: thomaschampagne/stravistix
Cc: geppoluc; Mention
Oggetto: Re: [thomaschampagne/stravistix] Multi activities in multisports fitness trend (#329)

 

Hi luca,

Does your ftp well entered in stravistix? I'm expreriencing same thing on strava fitness graph when use Trimp + PSS.

I also have same diff than you

PSS formula i use: https://github.com/thomaschampagne/stravistix/blob/develop/plugin/options/app/services/FitnessDataService.ts#L111

Which value other software (which one?) are giving you for 29/01 ?

(can't open your private? activity)

Tom

**Comment by thomaschampagne** [comment]
@geppoluc Yes i used it in the past. 

"(1) for the TRIMP and (2) for the TriScore." Do i am supposed to see some images? i yes can't see them.

In your case on 26/01 stravistix will use a value of 49 for the impulsion if powermeter option activated, else 87. I'm quite confident with calculation of TRIMP or PSS (or TSS trainingpeaks trademarked term)

Quoting this article:
http://home.trainingpeaks.com/blog/article/the-science-of-the-performance-manager

> Chronic training load, or CTL, provides a measure of how much an athlete has been training (taking into consideration both volume and intensity) historically, or chronically. It is calculated as an exponentially-weighted moving average of daily **TSS (or TRIMP, etc.)** values.

So it's seems to be PSS or TRIMP, no mix or fusion of them if you have both on same ride.

Maybe this require more documentation? Or someone more experienced in?

**Comment by geppoluc** [comment]
I know traininpeaks but I have never used it.  The problem in this discussion is that I do not know the subject and, for this reason, I’ll read the article carefully later, after work.

 

Does traininpeaks behave the same as Stravistix? If so (as I suppose), then the problem is me.

 

I am saying mixing/fusing because CTL is the “exponentially-weighted moving average of daily TSS (or TRIMP, etc.)”. So, if on day 1 you have the TRIMP and on day 2 you have the TSS, you are averaging (summing) the two (different?) objects. Or, as in my case, you have two different activities in the same day, one with TRIMP and the other with TSS, the CTL is the sum of the two.

 

I’m sorry for this discussion, I do not really want to make you lose time more than I already did.

 

Da: Thomas Champagne [mailto:notifications@github.com] 
Inviato: 01 February 2017 15:32
A: thomaschampagne/stravistix
Cc: geppoluc; Mention
Oggetto: Re: [thomaschampagne/stravistix] Multi activities in multisports fitness trend (#329)

 

@geppoluc <https://github.com/geppoluc>  Yes i used it in the past.

"(1) for the TRIMP and (2) for the TriScore." Do i am supposed to see some images? i yes can't see them.

In your case on 26/01 stravistix will use a value of 49 for the impulsion if powermeter option activated, else 87. I'm quite confident with calculation of TRIMP or PSS (or TSS trainingpeaks trademarked term)

Quoting this article:
http://home.trainingpeaks.com/blog/article/the-science-of-the-performance-manager

Chronic training load, or CTL, provides a measure of how much an athlete has been training (taking into consideration both volume and intensity) historically, or chronically. It is calculated as an exponentially-weighted moving average of daily TSS (or TRIMP, etc.) values.

So it's seems to be PSS or TRIMP, no mix or fusion of them if you have both on same ride.

Maybe this require more documentation? Or someone more experienced in?
