### ISSUE TITLE
Weekly totals

### ISSUE THREAD

**Issue by jdubcx** [thomaschampagne/stravistix#338]
As of couple of days ago the weekly training totals are not showing up on my main profile page. screenshot attached.
<img width="764" alt="screen shot 2017-02-19 at 7 05 38 am" src="https://cloud.githubusercontent.com/assets/25881564/23103063/eff0f6be-f671-11e6-9f0c-be5a6ffba3ba.png">

**Comment by iliuta** [comment]
Same here. 
Stravistix 5.4.2 and Chrome 56.0.2924.87 (64-bit).

**Comment by thomaschampagne** [comment]
I will disable this since it's pretty hard to maintain when strava change their html DOM.

Don't worry you will be able to get this back through dashboard feature. Grid feature (90% done)  may also do the work. Please be patient ;)

Tom

**Comment by iliuta** [comment]
Thanks Thomas. In that case it is better to disable it because the weekly/monthly statistics are completely hidden by the non working feature.
