### ISSUE TITLE
Code trys to run on API pages.

### ISSUE THREAD

**Issue by wolfpackt99** [thomaschampagne/stravistix#343]
Stravistix tries to run on pages that are meant to be api only. So jquery errors abound.

**Comment by thomaschampagne** [comment]
Do you have more info about this?
Errors displayed?

**Comment by wolfpackt99** [comment]
sure. i loaded one of the api urls to strava that my own custom app uses. The plugin (yours) trys to run on urls such as https://www.strava.com/api/* 

Maybe limit it to URLs that don't match the wild card.

**Comment by thomaschampagne** [comment]
OK solved for 5.7.0
