### ISSUE TITLE
Running power estimation as non-hidden feature

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#344]
```typescript
/**
 * Return a power estimation from athlete weight and speed (m/s)
 * @param {number} weightKg
 * @param {number} meters
 * @param {number} seconds
 * @returns {number} power watts
 */
public static estimateRunningPower(weightKg: number, meters: number, seconds: number): number {
    const minutes = seconds / 60;
    const km = meters / 1000;
    const pace = minutes / km;
    const VO2Reserve = 210 / pace;
    const VO2A = (VO2Reserve * weightKg) / 1000;
    const HWatts = (75 * VO2A);
    const VWatts = 0; //((9.8 * weight) * (elevationGain)) / (minutes * 60);
    return Math.round(HWatts + VWatts); // FIXME VWatts ?!
}

```
https://physics.stackexchange.com/questions/50097/power-of-a-runner

**Comment by thomaschampagne** [comment]
[Alan Couzens_ Run Power Calculator.pdf](https://github.com/thomaschampagne/stravistix/files/1289973/Alan.Couzens_.Run.Power.Calculator.pdf)
[Run Power Calculator _ Alan Couzens.pdf](https://github.com/thomaschampagne/stravistix/files/1289974/Run.Power.Calculator._.Alan.Couzens.pdf)

**Comment by PocketLloyd** [comment]
Hi Thomas, 
I know this is an old project for you, but like you I have looked at the Alan Couzen's Running Calculator.  I've been unable to contact Alan so I wonder if you would help me...  do you know where the "75" comes from in the line:
const HWatts = (75 * VO2A);
Many thanks
Lloyd
