### ISSUE TITLE
False Ctivity type

### ISSUE THREAD

**Issue by Bafff** [thomaschampagne/stravistix#348]
![image](https://cloud.githubusercontent.com/assets/26187677/23580294/78a397ee-010f-11e7-848b-31ccb2832439.png)
Here we can see Ride, Ride, Ride, but the first activity is a Run activity

**Comment by thomaschampagne** [comment]
I read RUN....ride ride :)

**Comment by Bafff** [comment]
I am very sorry, don't know how it may happen. )))
It is closed, of course!
