### ISSUE TITLE
rides show up for a second then gone

### ISSUE THREAD

**Issue by davidchasnoff** [thomaschampagne/stravistix#351]
**Bug description:** 
rides show up for a second then gone
**Actual Behavior:** 
this happened 2 updates ago, now it is back!
**Expected Behavior:** 
this stops when I disable the plug in.
**Steps to Reproduce:** 
- ...open strava
 - ...see ride flash
 - ...gone

**Chrome version** 
Version 57.0.2987.98
**Plugin version:** 
5.6.1 I think
**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
Do you have more info? Screenshsort? acitvitiy links? error console?

**Comment by davidchasnoff** [comment]
I don't know about error logs... but here are some screen shots. See the 
note below for details. Could this link help?
<iframe height='405' width='590' frameborder='0' 
allowtransparency='true' scrolling='no' 
src='https://www.strava.com/activities/894090237/embed/403a7139375e7618b76fc2885ebaaaeb46bf33bf'></iframe>
Thanks,
Dave


The first shot is with the plug in disabled, the next is after I enable 
it. My rides are gone and so are several others? Could have to do with 
where Strava is getting the data?
------ Original Message ------

**Comment by thomaschampagne** [comment]
Hi i can see any image from the ticket.

Could u upload them from github directly?

btw I loaded https://www.strava.com/activities/894090237 without problem.

Let me know,

Ty

**Comment by davidchasnoff** [comment]
Thanks for your reply, I turned the plug in back on today and it is 
working correctly. It is a great tool and I like it very much so it must 
be a bug with my computer. Thanks.
Dave

------ Original Message ------
