### ISSUE TITLE
No Yearly Progression on Dashboard

### ISSUE THREAD

**Issue by benoj** [thomaschampagne/stravistix#352]
**Bug description:** 

No Yearly Progression on Dashboard

**Actual Behavior:** 

Standard Strava yearly progression (not present as not premium user)

**Expected Behavior:** 

Stravistics annual progression breakdown

**Steps to Reproduce:** 

1) Log in
2) Go to dashboard.

**Chrome version** 
Google Chrome	56.0.2924.87 (Official Build) (64-bit)
Revision	0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@{#895}
OS	Linux 
JavaScript	V8 5.6.326.50

**Plugin version:** 

5.6.1

**Activities links?:** 
N/A
**Console errors? (press F12 to see developer console, and copy paste here):** 

None

**Comment by benoj** [comment]
Sorry was looking in the wrong place infact. Think this could be useful on the main activity feed too

**Comment by thomaschampagne** [comment]
ok :) np
