### ISSUE TITLE
Elevation delta shows 'undefined' as units

### ISSUE THREAD

**Issue by tjsr** [thomaschampagne/stravistix#356]
**Bug description:** 
On the mouse-over for the up or down arrow for yearly progression details, the unit for elevation shows 'undefined' after the value, eg, "-4,361 undefined".  It should say "-4,361 metres". The numeric value appears to be correct, but it does not get the correct string for the unit of mesaurement.

**Actual Behavior:** 
Value is displayed as "-4,361 undefined".

**Expected Behavior:** 
The value shown should use the measurement metric based on the users region, ie, feet or metres, or if not set/detected, use a default.  

**Steps to Reproduce:** 
- Go to the user profile page and scroll down so you can see the 'My year progression to current month/day' section.
 - Hover your mouse over the up or down icon for a year in the 'elevation' column.

This might only occur when there's a value not set in the users settings - it might require clearing any browser settings cached?  It also might only occur on metric, as that's what I'm using to cause this.

**Chrome version** 
All, but current is 56.0.2924.87

**Plugin version:** 
5.6.1 Stable and recent versions.

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 
None

**Link screenshots or youtube video link if necessary:**
![image](https://cloud.githubusercontent.com/assets/26394468/23880144/d662a0bc-08a5-11e7-9324-d6d83f987c84.png)

**Comment by thomaschampagne** [comment]
This feature has been remade inside #328 

Bug should be auto fixed ;)
