### ISSUE TITLE
PSS reduses fatigue?

### ISSUE THREAD

**Issue by Filliny** [thomaschampagne/stravistix#357]
**Bug description:** 
Using powermeter reduses fatigue calculation
so - equal activities, where one of them was without pm - have more fatigue on grapf
same as i disable or enable power meter usage for calculation fitness- 
see creenshots
http://i.imgur.com/0x1UZIb.jpg
http://i.imgur.com/X4YxRKL.jpg
Plugin version actual , chrome version last...

**Comment by thomaschampagne** [comment]
Why did you close it?

Maybe a too high FTP enterred?

**Comment by Filliny** [comment]
Ftp is fine) Closed cos - i check fitness and freshness from strava - it have the same behavior...
 cos calculation from HR is TSS, and from HR+PM  is TRIMP - and when we use only HR during activity then tss is allways higer number than TRIMP... that is no issue - it is dificult to take right handling of two different models of fatigue calculation on one graph, so i decide that right practice will be use ONLY hr - TSS is most useful number - i use it on Traineroad, Training peaks an other... Not sure what uses Polar on Flow, but they too HR masters, so HR is main... But if u want to take case to the end - right behavior is when the same activity loaded on two different days, one with HR, second HR+PM must have close numbers of fatigue... i think so... but its all need to to testing and analyzing deeper with understanding all formulas and calculations... i have no dig so deep now)

**Comment by jayti74** [comment]
look at #341discussion
