### ISSUE TITLE
New Year to date progression gives wrong value for hours

### ISSUE THREAD

**Issue by gethin88** [thomaschampagne/stravistix#363]
My running in 2014 suddenly shows a time increase over 1000 hours on one day:
![image](https://cloud.githubusercontent.com/assets/11189817/24094050/3c3e94f8-0d57-11e7-8d39-6fc80087de55.png)

The activity in question: https://www.strava.com/activities/127518511/overview

Issue still present after full resync

**Comment by thomaschampagne** [comment]
@gethin88 Could you upload here your history as zip ?

Stravistix UI > Clock icon > backup history

Ty

**Comment by xanadonf** [comment]
Your activity shows an elapsed time of 1168:59:25

**Comment by gethin88** [comment]
Indeed, overlooked that, was looking for it, but didn't find it before.

Checked on garmin connect, seems to be the issue there as well, is it possible to edit this in strava?

**Comment by xanadonf** [comment]
Strange behavior. Maybe in cropping both start and end of the activity (ten seconds each)?
If not, in exporting gpx, fixing manually the problem in the xml file, then importing it in Strava (more complex).

**Comment by gethin88** [comment]
Issue was in the beginning, cropped the activity and it's fixed now.
Changing time zones caused the error. Started the activity before the watch found gps signal, therefor still using wrong data I assume untill it corrected itself when the signal was found.
Issue resolved, was on my end, apologies!
