### ISSUE TITLE
Year progressions

### ISSUE THREAD

**Issue by taston** [thomaschampagne/stravistix#364]
![image](https://cloud.githubusercontent.com/assets/22216384/24094508/491c7ea4-0d59-11e7-8a67-77636f6843af.png)

**Comment by biejoo** [comment]
I don't understand what the issue is you are trying to explain.

**Comment by thomaschampagne** [comment]
Same to me. What does this panel:
>This panel displays your progress for each beginning of year to current month and day. Today is March 20th, this panel shows "What I've accomplished by March 20th of this year compared to previous years to the same date."

**Comment by taston** [comment]
My mistake. I was thinking that all rows is comparison to this year. Now I understand what means "Δyear-1".
