### ISSUE TITLE
Changing from km --> miles

### ISSUE THREAD

**Issue by pawel31415** [thomaschampagne/stravistix#366]
I can't seem to find how to do it. Please help.

**Comment by Jmorjsm** [comment]
This can be done in the [Strava display settings](https://strava.com/settings/display) by changing the units and measurements

**Comment by mbartenschlag** [comment]
@Jmorjsm, I just confirmed that I have selected Miles and Pounds there, but the Year Progressions graph continues to display using kilometers. The drop-down only provides Distance (km), but I think @pawel31415 and I are looking for Distance (miles)!

**Comment by bsvensson** [comment]
I too would also like to see the Year Progressions in miles / take advantage of the [units in Strava Display Preferences](https://www.strava.com/settings/display).

**Comment by bhuskey** [comment]
Another vote for adding an option to view in Miles.

**Comment by thomaschampagne** [comment]
Fixed in new app :)
