### ISSUE TITLE
raceshape.com no longer works

### ISSUE THREAD

**Issue by Arganaz** [thomaschampagne/stravistix#367]
it reports "server error" when acessing either the link for export, or accessing directly to http://wwwhttp://raceshape.com/
I believe it was bought by strava

**Comment by geromey** [comment]
It has now a different error which doesn't seem any better : 

> Warning:  file_put_contents(/vol/cache/rides/1488/243/full.json): failed to open stream: No such file or directory in /www/raceshape/shape/includes/fileio.inc.php on line 78 Warning: chmod(): No such file or directory in /www/raceshape/shape/includes/fileio.inc.php on line 79 Warning: file_put_contents(/vol/cache/rides/1488/243/extra.json): failed to open stream: No such file or directory in /www/raceshape/shape/includes/fileio.inc.php on line 78 Warning: chmod(): No such file or directory in /www/raceshape/shape/includes/fileio.inc.php on line 79 {"error":"Strava not available"}

**Comment by thomaschampagne** [comment]
I re-developed the feature by myself. 

You can try with a test build here: https://ci.appveyor.com/project/thomaschampagne/stravistix/branch/develop/artifacts

How to install: https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

(I'm able to see downloaded courses on my edge 1000)

**Comment by geromey** [comment]
I exported and uploaded a gpx to my fenix 5. The map and elevation is shown correctly, as well as distance and time of the effort.

I still have not tried it on a ride but I'm confident that it will work well.

Thank you Thomas !

**Comment by geromey** [comment]
I tried to export this effort and it has a javascript error : 

https://www.strava.com/activities/158017059/segments/3657729681

VirtualPartnerModifier.js:112 Uncaught TypeError: Cannot read property '0' of undefined
    at VirtualPartnerModifier.genGpxData (VirtualPartnerModifier.js:112)
    at VirtualPartnerModifier.createGpxAndSave (VirtualPartnerModifier.js:85)
    at VirtualPartnerModifier.js:80
    at VacuumProcessor.getActivityStream (VacuumProcessor.js:158)
    at VirtualPartnerModifier.js:74
    at Object.<anonymous> (VirtualPartnerModifier.js:52)
    at Object.<anonymous> (strava-head-15339e2….js:2)
    at c (strava-head-15339e2….js:2)
    at Object.fireWith [as resolveWith] (strava-head-15339e2….js:2)
    at n (strava-head-15339e2….js:3)

**Comment by geromey** [comment]
I saw that you fixed this issue in your last commit actually.

it was quick.
