### ISSUE TITLE
3rd party TRIMP score differs based on user id?

### ISSUE THREAD

**Issue by rtismeer** [thomaschampagne/stravistix#371]
**Bug description:** 
Based on what I see, a 3rd party's TRIMP score is based on my values
**Actual Behavior:** 
I log in to Strava, look at 3rd party ride stats ... shows TRIMP of 401 
I tell a friend; he logs in, views same 3rd party ... his stats show a TRIMP of 287
**Expected Behavior:** 
Unsure? Am I missing the point of this or is it wrong?
**Steps to Reproduce:** 
- ...View this (if you can) with your account: https://www.strava.com/activities/887806428
 - ...Have someone else view it using their account
 - ...Note the differences in TRIMP value

**Chrome version** 
Version 57.0.2987.110
**Plugin version:** 
5.7.1 Stable
**Activities links?:** 
https://www.strava.com/activities/887806428
**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**
![tomb](https://cloud.githubusercontent.com/assets/26632000/24262155/6fc2e7aa-0fb6-11e7-95e0-000e321e73fa.png)
![tomb_brian2](https://cloud.githubusercontent.com/assets/26632000/24262159/76106a38-0fb6-11e7-92f0-1546bfbcb651.jpg)

**Comment by thomaschampagne** [comment]
Because you are not using same HRMax/HRMin => affect %HRR => affect TRIMP calculations.

>When you don't own an activity notice that TRaining IMPulse, %HRR Average and distribution graph are computed from your StravistiX health settings.
This allows you to analyse your heart capacity with the data recorded on the activity of this athlete.

**Comment by thomaschampagne** [comment]
What are you hr max/min?

I have trimp 282 with 200/50

**Comment by rtismeer** [comment]
Gotcha, that's kinda what I figured, 'cause then I'd be seeing his numbers,
etc.
My HR Max is 172/57
