### ISSUE TITLE
Time in decimal form instead of HH:MM

### ISSUE THREAD

**Issue by ilyaguy** [thomaschampagne/stravistix#380]
In Year Progression panel table below chart contains 'Time (h)' and '∆ year -1' columns.

The time is rendered in decimal form (4.5 hours, e.g.)
But it is more usable to render it in form HH:MM (4:30 for the case).

**Steps to Reproduce:** 
Open the "Year Progression" panel and scroll to the bottom.

**Chrome version** 
Chrome 53.0.2785.116 (64-bit)

**Plugin version:** 
5.7.1 Stable

**Console errors? (press F12 to see developer console, and copy paste here):** 
No console errors.

**Link screenshots or youtube video link if necessary:**
<img width="243" alt="2017-04-06 18 08 08" src="https://cloud.githubusercontent.com/assets/6704355/24761445/074ca2ee-1af4-11e7-91a0-f429818f1444.png">

**Comment by thomaschampagne** [comment]
Released in 5.9.0
