### ISSUE TITLE
relive.сс link

### ISSUE THREAD

**Issue by ilyaguy** [thomaschampagne/stravistix#383]
Could you implement link to relive.cc video, if the video is presented?

The video page url format is `https://www.relive.cc/view/%ride_id%`
If there's no video, relive will return http 404 code.

Relive.cc video creating conditions: distance is longer than 10 km and ride time is smaller than 12 hours. So, I think the plugin may not check relive website if the ride does not fit there conditions.

**Comment by thomaschampagne** [comment]
You Right. I'm also waiting for relivecc that they handle non existing video on a ride.
