### ISSUE TITLE
Missing activities in the '' MultiSports Fitness Trend'' 

### ISSUE THREAD

**Issue by JayBiker** [thomaschampagne/stravistix#401]
In the MultiSport Fitness Trend tool, it missing activities in the graph. But, these activities are display in the Year progress tool.

**Comment by stefanvn** [comment]
I have the same issue

**Comment by ct2034** [comment]
In the trend only activities with heart rate data show up. Do your missing activities have heart rate data?

**Comment by thomaschampagne** [comment]
Any news ? Closing it. re-open if needed
