### ISSUE TITLE
How do I get started customizing zones settings to get more coherent results? 

### ISSUE THREAD

**Issue by Fandekasp** [thomaschampagne/stravistix#404]
Hi Thomas,

Hats off for this amazing app. Although it looks a bit overwhelming to the non-initiated, I'd like to get more familiar with it and make it a helpful tool to manage my training load.

Currently, the "Multisports Fitness Trend" is showing me:
![2017-06-07_14-36-08](https://user-images.githubusercontent.com/260983/26863611-ac4f7f8a-4b8e-11e7-8d3d-1cb95126f01f.png)

I do feel a bit tired, but l'm probably not in over load. My Garmin 935 reports VO2Max: 54, Recovery: 0 hours (train as usual), Training load (Last 7 days 324: low).
It might be the garmin device which is incorrect, so I'd like to dig deeper into it. 

Did you maybe write a blog post on how to get started with the app, or are there tips somewhere to increase the data evaluation's accuracy?

**Comment by duhlig** [comment]
The Fitness-Fatigue-Model needs data from at least 42 calendar days to become useful. The zones are based on power (TSS). If you're training with heart rate only you'll likely overshoot the zones more often, but the general trend is still reliable. Consider reading Dr. Coggan's book if you want to dig deeper.

**Comment by Fandekasp** [comment]
Got it, will wait for the 42 days then, thank you :) Closing
