### ISSUE TITLE
Some activities not showing on Stravistix!

### ISSUE THREAD

**Issue by ossolisergio** [thomaschampagne/stravistix#409]
**Bug description:** 
The activities from 13may to 25 may aren't showing on my stravistix multisport fitness tool while all other strava activities are shown, it's quite annoying cause the result is a graph that's not realistic at all so it become totally unuseful 
**Actual Behavior:** 
Recent activies are showing, just the ones from 13-25 may period aren't
**Expected Behavior:** 
i expect to see all my activities so i can obtain a realistic graph
**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
58.0.3029.110 (64-bit)
**Plugin version:** 
5.7.2 Stable
**Activities links?:** 
https://www.strava.com/activities/986286820
https://www.strava.com/activities/994412597 and many others
**Console errors? (press F12 to see developer console, and copy paste here):** 
no errors registred
``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**
![immagine](https://user-images.githubusercontent.com/29583693/27355535-a96c20de-560b-11e7-908a-f522fe1cc1de.png)   

as you can see there's a big hole in period 13-25 , i registred a lot of activities during that period

**Comment by thomaschampagne** [comment]
As written in feature infos/note you need hr monitor

>Here you will be able to view your fitness trend using all activities where you held a heart rate monitor.

Hold one next time ;) :)
