### ISSUE TITLE
Extended statistics are not displaying minutes and seconds correctly

### ISSUE THREAD

**Issue by MaximeKjaer** [thomaschampagne/stravistix#413]
![image](https://user-images.githubusercontent.com/990794/27727192-ad0fe0e4-5d7d-11e7-961d-a7cf02240088.png)

5:60 should probably be 6:00 😉 Maybe a rounding error?

**Comment by thomaschampagne** [comment]
Do you have an activity id?

**Comment by MaximeKjaer** [comment]
https://www.strava.com/activities/1056886040

**Comment by thomaschampagne** [comment]
Fixed in 5.9.0 ;)
