### ISSUE TITLE
"Export segment effort for GPS device" not compatible with Edge 500

### ISSUE THREAD

**Issue by akp12345** [thomaschampagne/stravistix#424]
The new "Export segment effort for GPS device" is a welcome fix for raceshape VPU no longer functioning. However, it is not directly compatible with Edge 500. Edge 500 wants a TCX course whereas the current output is GPX only. The workaround at present is to export GPX and use GPSBabel or equivalent to convert to TCX course (that works adequately). In future the option to export as TCX in addition to GPX would be very much appreciated!

**Comment by thomaschampagne** [comment]
Ok thanks for report :)
