### ISSUE TITLE
Rides not shown in multisports fitness trend

### ISSUE THREAD

**Issue by robarov** [thomaschampagne/stravistix#428]
**Bug description:** 
4 subsequent rides are not shown in the multisports fitness trend graph. These rides do include HR data.
**Actual Behavior:** 
Days are marked as restdays
**Expected Behavior:** 
Rides are shown, impact on fitness trend calculated.
**Steps to Reproduce:** 
 - Sync manually
 - Go to Multisports Fitness Trend
 - Rides are missing

**Chrome version** 
Versie 59.0.3071.115 (Officiële build) (64-bits)
**Plugin version:** 
v5.9.0
**Activities links?:** 
- https://www.strava.com/activities/1102452983/overview
- https://www.strava.com/activities/1104167329/overview
- https://www.strava.com/activities/1105709883/overview
- https://www.strava.com/activities/1106703137/overview

**Console errors? (press F12 to see developer console, and copy paste here):** 
No

**Link screenshots or youtube video link if necessary:**
<img width="514" alt="schermafbeelding 2017-07-31 om 11 33 39" src="https://user-images.githubusercontent.com/869705/28771726-277fb182-75e4-11e7-954f-8f81c38b135f.png">

**Comment by robarov** [comment]
Nevermind, a full re-sync did the trick. Keep up the great work!

**Comment by thomaschampagne** [comment]
perfect :)
