### ISSUE TITLE
TCX output should be Course not Activity; TCX TotalTimeSeconds and DistanceMeters are from start of activity, not start of segment

### ISSUE THREAD

**Issue by adamkpearce** [thomaschampagne/stravistix#433]
Edge 500 wants the TCX output as a Course not an Activity. 
Furthermore, the TotalTimeSeconds and DistanceMeters in the "Lap" appear to be from start of activity (i.e. start of ride) not start of segment. That creates errors in the course distance and profile displays.

I have a patch to fix the issues in CourseMarker.ts against commit 43cf7d4d5d03b324c1f0d3bc0f1546666aff4ece. 

Should I generate a pull request? I confess I am rather new to git. I have attached the patch. It also tidies up a couple more things to make the file look more like known working TCX courses generated by ridewithgps.com, strava.com, and GPSBabel.

[CourseMarker_patch.txt](https://github.com/thomaschampagne/stravistix/files/1203732/CourseMarker_patch.txt)

**Comment by thomaschampagne** [comment]
@adamkpearce Thanks for your feedback ! Could you provide me git diff patch instead? Like this:
>_~/Documents/Projects/stravistix (develop)$_ **git diff > fix.patch**

**Comment by thomaschampagne** [comment]
... Or just send your complete file as a simple solution.

Thanks for your work and help :)

Tom

**Comment by adamkpearce** [comment]
My file is attached; I will have to get up and running in the proper dev stream if I find something else to work on. I missed the raceshape VPU for segment comparisons when it went down so I very much appreciate you adding this feature.

[CourseMarker.zip](https://github.com/thomaschampagne/stravistix/files/1206222/CourseMarker.zip)

**Comment by thomaschampagne** [comment]
Thanks 👍 ! Did you test your produced TCX against Garmin TCX XSD?

**Comment by adamkpearce** [comment]
It appears I am getting some errors against the XSD. I will fix them and re-upload later today.

**Comment by thomaschampagne** [comment]
@adamkpearce Thanks for your work 👍 👍 👍  :)

**Comment by adamkpearce** [comment]
The tcx is passing the xsd now. I have also removed the fields that aren't necessary for virtual partner, which makes the file about half the size (copies to Edge 500 a little faster). These are changes:
- Limited course name to 15 characters
- Reduced Lap fields to mandatory (TotalTimeSeconds, DistanceMeters, Intensity)
- Reduced Trackpoint fields to Position, AltitudeMeters, DistanceMeters
- Removed unnecessary rounding

[CourseMarker.zip](https://github.com/thomaschampagne/stravistix/files/1216740/CourseMarker.zip)

**Comment by adamkpearce** [comment]
We can add the heart rate, speed, watts, etc fields back in if anyone can make use of them in a course file.

**Comment by adamkpearce** [comment]
I just saw now that my edits will cause the CourseMaker.spec.ts to fail... not sure if you want the deleted fields back in or if you want to change the CourseMaker.spec.ts file accordingly.

**Comment by thomaschampagne** [comment]
You did it right ! I updated my unit tests. Very thanks 👍 

Tom
