### ISSUE TITLE
Some activities missing in Multisport fitness trend (especially longer ones)

### ISSUE THREAD

**Issue by cwasmer** [thomaschampagne/stravistix#436]
**Bug description:** 
Some of my activities are not reflected in the multisport fitness trend, but they contribute in the year progression graph
**Actual Behavior:** 
as described
**Expected Behavior:** 
All activities should be considered for the fitness trend
**Steps to Reproduce:** 
- Load Strava activities
 - Click Multisport fitness trend. Mouseover does not show all my activities
 - Year progression clearly shows all activities

**Chrome version** 
58.0.3029.110
**Plugin version:** 
5.10.1 Stable
**Activities links?:** 
e.g. https://www.strava.com/activities/1119030650
**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
You don't have HR data on this activity. You must have to get it in the trend.

Tom
