### ISSUE TITLE
Partial Sync

### ISSUE THREAD

**Issue by ahsmho** [thomaschampagne/stravistix#441]
**Bug description:** 
I use my garmin device to track my activity, cycling,running,swimming. But i did two runs using strava app and did not used my tracking GPS watch.  I am noticing that run not done through Garmin device is not synced.
**Actual Behavior:** 

**Expected Behavior:** 

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
Versjon 60.0.3112.90 (Offisiell delversjon) (64-bit)
**Plugin version:** 
Additional Information
Version: 2.8.0
Updated: July 26, 2017

**Activities links?:** 
https://www.strava.com/activities/1142614387
https://www.strava.com/activities/1137107067
https://www.strava.com/activities/1133715948

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
@ahsmho Same behaviour than https://github.com/thomaschampagne/stravistix/issues/469
