### ISSUE TITLE
Variability Index calculation error due to incorrect average power?

### ISSUE THREAD

**Issue by harnbak** [thomaschampagne/stravistix#444]
Hi - thx for a great plugin. 

Variability index (VI = the fraction of normalised power and average power) is sometimes calculated incorrectly. 

For this strava activity: https://www.strava.com/activities/1149931366 VI is determined to be 1.12: 
![image](https://user-images.githubusercontent.com/31338004/29703417-cc56b652-8975-11e7-8396-7648b91e62e9.png)
VI should have been 297 / 274 = 1.08: 
![image](https://user-images.githubusercontent.com/31338004/29703460-ef707092-8975-11e7-855d-e0c3f497dbba.png)
This is also confirmed by Training Peaks: 
![image](https://user-images.githubusercontent.com/31338004/29703647-b0bfb35c-8976-11e7-9994-da970147ac36.png)

Please investigate and let me know if more info is needed.

**Comment by harnbak** [comment]
It seems to me that average power as used by StravistiX is the problem. 

In the first screenshot Avg Watts/Kg is calculated by StravistiX as 3.41. 
My weight has been specified in StravistiX as 78 kg: 
![image](https://user-images.githubusercontent.com/31338004/29704153-daf3e83a-8978-11e7-826b-248054fa702c.png)
This implies that Avg Watts as used by Stravistix is 3.41 x 78 = 266. 
VI is then calculated as 297 / 266 = 1.12 as confirmed by the first screenshot. 

But average power is actually 274 W, please see second screenshot form Strava. This number is confirmed by Garmin Connect and Training Peaks.

**Comment by thomaschampagne** [comment]
@harnbak Thx for report and sry the delay of fixing

**Comment by harnbak** [comment]
Looks fine now, thx
