### ISSUE TITLE
Question:   Average Pedaling Pace  Calculation

### ISSUE THREAD

**Issue by hellergang** [thomaschampagne/stravistix#446]
Hi,

I love your Strava enhancements and pages!

I am looking for a specific statistic.  I'll call it Average Pedaling Pace (just cuz its alliterative!)

I am not sure if average pace does this or not.

So, when I am going downhill and not pedaling, and therefore going faster I don't want to count that speed in my pace calculation.  I want a statistic that shows my avg pace ONLY when I am exerting effort - pedaling.  It's kinda like "avg climbing speed," but that's just for climbing.  I'd like to see a number for the non-climbing pace and even a combined all around pace while I am pedaling. I suppose it counts if I am pedaling downhill also, but that's not as much effort.

I suppose that this is what watts are all about, but I don't have a watt meter.  Should I really be thinking down that path?  It's similar, but different than pace.  But, I can see that maybe I should focus my attention on watts. Net net.  I want to see how hard I am working

What do you think about all this?

Thanks, Peter

**Comment by thomaschampagne** [comment]
To sum up you need:

- [ ] Cadence average pace in downhill in RPMs
- [ ] Cadence average pace on flat in RPMs
- [ ] Cadence average pace while climbing in RPMs

??

Tom

**Comment by thomaschampagne** [comment]
Done :)
