### ISSUE TITLE
Apple Watch stats does not match stats in uploaded activity

### ISSUE THREAD

**Issue by codyhcox** [thomaschampagne/stravistix#453]
**Occasionally my Apple watch will report accurately the time and distance, but after saving and syncing with phone the uploaded activity does not match.  See Screen Shots Below.  I've started taking a picture of my watch before saving to retain accurate results** 

**Steps to Reproduce:** 
- ...
![uploaded stats](https://user-images.githubusercontent.com/31773011/30219324-59d51a30-9481-11e7-9073-b408c31fede8.JPG)
![watch](https://user-images.githubusercontent.com/31773011/30219325-59d58d94-9481-11e7-85fc-d74792c43f7d.jpg)

 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by philipwhiuk** [comment]
This is a Strava choice not a Stravistix issue. Note 'Moving Time'. What does Strava show if you change the activity type to 'Race'.

**Comment by codyhcox** [comment]
I disagree, I did not stop or pause during this run and auto pause is
disabled.  Changing to race does not change anything.  To me it appears
once uploaded the first ~2 minutes are not included, verified by the gps
map.   It also only seems to occur when I start the run next to a major
highway, maybe interference.  I do Agree this may not be a stravistix
issue, the bug may have been filed in the wrong location.

**Comment by thomaschampagne** [comment]
I can't fix anything there even if i would like to :( Strava side for sure.
