### ISSUE TITLE
End Anachronistic Analysis of Data

### ISSUE THREAD

**Issue by MrModenait** [thomaschampagne/stravistix#456]
In it's current form, whenever I update my athlete data on Stravistix, syncing my data recalculates TRIMP scores and various other metrics on my old rides – using my new athlete profile settings. I find it questionable that Stravistix re-analyses old rides using new data, because fitness changes over time – what was an easy ride back then might've been a hard ride with today's athlete profile, and vice versa. For this reason I believe that old rides should not have their metrics re-calculated when athlete profile is changed.

**Comment by thomaschampagne** [comment]
Re syncing local history is required when you update your settings (which are cloud saved).

Unfortunatly strava don't store your hr max/min & ftp for each rides. So you can't recompute your TRIMP & TSS values for each ride based your "fitness snapshots" in the past.

Official strava fitness & freshness suffer the same problem.

Hope this helps !
