### ISSUE TITLE
No error reported when sync fails due to full harddrive.

### ISSUE THREAD

**Issue by theed** [thomaschampagne/stravistix#457]
**Bug description:** 
Failure when synchronizing with full harddrive produces no error or indication that synchronization failed.

**Actual Behavior:** 
When HD is full when syncing, no apparent issues are being reported, but the graph is missing the latest updates. Only tested when previous synchronizations are available locally.

**Expected Behavior:** 
Error message or notification when latest activities does not get synced properly.

**Steps to Reproduce:** 
Fill up HD with junk and windows update-garbage.
Resync.

**Chrome version** 
Version 62.0.3202.9 (Officiell version) dev (64 bitar)

**Plugin version:** 
Don't know. Latest as of september 9th.

**Comment by thomaschampagne** [comment]
@theed Thanks for report 
I would say that this warning has to come from windows, MacOS or linux before this web plugin :)
