### ISSUE TITLE
Strava Achievement is broken

### ISSUE THREAD

**Issue by vd67** [thomaschampagne/stravistix#470]
Result message :
Summary
Not leading any segments :(

**Comment by thomaschampagne** [comment]
Could you give more details? :)

**Comment by vd67** [comment]
Hello, when a use the KOM/CR MAP fonctionality for the athlete ID 6294914, he said "Not leading any segments :( ". Under Strava the athele has more than 190 QOM, Thank's.

**Comment by thomaschampagne** [comment]
Damn this strava labs feature is not working anymore .. :/

**Comment by thomaschampagne** [comment]
It's strava feature side. Can't fix it. closing it
