### ISSUE TITLE
dKOM showing NaN

### ISSUE THREAD

**Issue by palunel** [thomaschampagne/stravistix#474]
**Bug Descripton**
On the Ride page with list of all segments a number of the delta KOM times are shown as NaN.

**Chrome version**
Version 61.0.3163.100 (Official Build) (64-bit)

**Plugin version:** 
5.12.0 stable

![capture](https://user-images.githubusercontent.com/33368866/32403910-ebbc083e-c14d-11e7-9996-33e84d85c767.PNG)

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
@palunel Thx for report

**Comment by compmaster** [comment]
This issue occurs when server sends `"N/A"` string in field `kom_time` of JSON response.
