### ISSUE TITLE
Can't hide bike/run activities under a certain milage

### ISSUE THREAD

**Issue by morefilters** [thomaschampagne/stravistix#476]
I have selected both run and rides under 9 miles to be hidden, but they still appear in my feed? Is there a fix for this? Thanks for all that you have done. It's way better thanks to you.

**Comment by Filliny** [comment]
Yes - same issue for me  - set cycling dist to 10 km - but they still appear in feed. And add please "Hide Commutes"

**Comment by thomaschampagne** [comment]
I'm not able to reproduce using 6.1.0 version

Are you using same version?

**Comment by thomaschampagne** [comment]
Any update on this? Can i close?
