### ISSUE TITLE
Activity Search not returning results or map displays

### ISSUE THREAD

**Issue by ShaneRing** [thomaschampagne/stravistix#492]
**Bug description:** 
No map loading or routes on the Activity Search page in Chrome or Safari browsers. 

Screenshot: http://take.ms/Phqa6

Live link not working: https://www.strava.com/activities/search?utf8=%E2%9C%93&location=San+Diego%2C+California&%5Bcountry%5D=United+States&%5Bstate%5D=California&%5Bcity%5D=San+Diego&%5Blat_lng%5D=32.715738%2C-117.16108380000003&keywords=&activity_type=All&type=&distance_start=0&distance_end=200&time_start=0&time_end=10&elev_gain_start=0&elev_gain_end=15000

**Actual Behavior:** 
No map or search results loading

**Expected Behavior:** 
Map and search results should load.

**Steps to Reproduce:** 
1) Go to URL: https://www.strava.com/activities/search?utf8=%E2%9C%93&location=San+Diego%2C+California&%5Bcountry%5D=United+States&%5Bstate%5D=California&%5Bcity%5D=San+Diego&%5Blat_lng%5D=32.715738%2C-117.16108380000003&keywords=&activity_type=All&type=&distance_start=0&distance_end=200&time_start=0&time_end=10&elev_gain_start=0&elev_gain_end=15000

2) Click search
3) Nothing loads

**Chrome version** 

Version 63.0.3239.108 (Official Build) (64-bit)

**Plugin version:** 

NA

**Activities links?:**

See above

**Console errors? (press F12 to see developer console, and copy paste here):** 

http://take.ms/ugmgn

2jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/?file=gdata&v=1.x, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22
P.load @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:30
google.load @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:18
(anonymous) @ search?utf8=✓&location=San+Diego%2C+California&[country]=United+States&[state]=California&[city]=San+Diego&[lat_lng]=32.715738%2C-117.16108380000003&keywords=&activity_type=All&type=&distance_start=0&distance_end=200&time_start=0&time_end=10&elev_gain_start=0&elev_gain_end=15000:1002
2jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/api/gdata/1.10/208a907929e7936990d2bf48205aa8d8/core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22
(anonymous) @ ?file=gdata&v=1.x:8
inject.js:207 Uncaught TypeError: Cannot read property 'body' of null
    at initializeNow (inject.js:207)
    at window.onload (inject.js:191)
initializeNow @ inject.js:207
window.onload @ inject.js:191
search?utf8=✓&location=San+Diego%2C+California&[country]=United+States&[state]=California&[city]=San+Diego&[lat_lng]=32.715738%2C-117.16108380000003&keywords=&activity_type=All&type=&distance_start=0&distance_end=200&time_start=0&time_end=10&elev_gain_start=0&elev_gain_end=15000:1 Refused to execute script from 'https://analytics.twitter.com/i/adsct?p_id=Twitter&p_user_id=0&txn_id=nufpt&tw_sale_amount=0&tw_order_quantity=0&tw_iframe_status=0&tpx_cb=twttr.conversion.loadPixels&cache_bust=0.0637308773673102' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Link screenshots or youtube video link if necessary:**

http://take.ms/sWBxj

**Comment by ShaneRing** [comment]
Whoops, thought I was submitting a bug to Strava just now.

**Comment by thomaschampagne** [comment]
Ok perfect :)
