### ISSUE TITLE
COM/CR-Map

### ISSUE THREAD

**Issue by DonCarracho** [thomaschampagne/stravistix#496]
**Bug description:** 
The Strava Achivement Map [COM/CR-Map] doesn't work anymore.
No Bug with stravistix but a Strava Issue since Strava changed the way of sroring segment in the mid of october as to be seen here:
https://medium.com/strava-engineering/rebuilding-the-segment-leaderboards-infrastructure-part-1-background-13d8850c2e77
Is there any way, to make the guys at Strava make this work again?
I learn it's a free time project of their developers and "not part of the product".
But mayby if you tell them?
Would be really appreciated!
**Actual Behavior:** 
"Leading no Segments :(" is shown. For every athlete, even if leading hundres of sgements...
**Expected Behavior:** 
CR-Map
**Steps to Reproduce:** 
- Open COM/CR-Map in stravistix plugin
 - ...
 - ...

**Chrome version** 
 63.0.3239.84
**Plugin version:** 
5.12.1
**Activities links?:** 
https://labs.strava.com/achievement-map/#14621121/run/13/7.04945/51.07657
**Console errors? (press F12 to see developer console, and copy paste here):** 
No stavistix bug - bug exist, when openeing achivement map via labs.strava.com, too.
``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
Indeed feature doesn't work anymore? I'm returning the question then.. :/

From now, nothing has be replaced to cover this by strava?
