### ISSUE TITLE
Metric vs. Imperical

### ISSUE THREAD

**Issue by kleinen12** [thomaschampagne/stravistix#497]
No way ( at least no obvious way ) to change the measurements in the year progressions from Metric to Imperical

N/A

N/A

Go to Yearly Progressions and try to look at Distance, Time, Elevation or Count in Empirical units.  There is no obvious way ( or no way at all ) to change this to Empirical units.

**Comment by thomaschampagne** [comment]
I will soon release a brand new version of the app. All recoded from scratch. I added imperial support. Work is done. Just wait few days or 2/3 weeks

**Comment by kleinen12** [comment]
Excellent!  Thanks for your hard work!
________________________________
