### ISSUE TITLE
Typo: in Power Data // Weighted Power (or estimated...): one section is titled "Power Score Score:" not "Power /Stress/ Score:"

### ISSUE THREAD

**Issue by easilydistracte** [thomaschampagne/stravistix#499]
**Bug description:** 
As title - just a typo when the help tab is opened describing what the extended stats mean and how they are calculated
**Actual Behavior:** 
"Power Score Score:" is displayed
**Expected Behavior:** 
Power Stress Score: should be displayed
**Steps to Reproduce:** 
- ...on any Strava ride, click on Power Stress Score to open up the new tab with the errant writing on it
 - ...
 - ...

**Chrome version** 
63.0.3239.132
**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
Thx for report
