### ISSUE TITLE
Virtual rides stats

### ISSUE THREAD

**Issue by SirAlexey** [thomaschampagne/stravistix#501]
**Bug description:** 
Year progressions graph does not count virtuals rides statistics for Ride type activites.

**Actual Behavior:** 
When i select only "Ride" on "Activities types" list i did not see counts and distance for my virtual rides, recorded with Zwift.

**Expected Behavior:** 
I expected to see my virtial rides counts to ride type activities.

**Steps to Reproduce:** 
- ...
 - ...
 - ...

**Chrome version** 
63.0.3239.132

**Plugin version:** 

**Activities links?:** 
https://www.strava.com/activities/1358509365
**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by SirAlexey** [comment]
I'm dumb, sorry.
All was needed was to select both types of activities "Ride" + "Vitual Ride"

**Comment by thomaschampagne** [comment]
No problem :)
