### ISSUE TITLE
Predict TRIMP for workouts without heart rate 

### ISSUE THREAD

**Issue by ct2034** [thomaschampagne/stravistix#513]
The fitness trend currently ignores workouts with no heart rate data. This could be fixed for those that have used a heart rate monitor before by predicting the TRIMP based on previous workouts. The model could be as easy as an average TRIMP /h up to something depending on sport, speed and gradient

**Comment by thomaschampagne** [comment]
@ct2034 Thanks for report.
Closing it & keeping link with #314 (planned)

**Comment by clemrider** [comment]
Hi,

So how modify the trimp  ?
