### ISSUE TITLE
Triplicate Functionality on screen

### ISSUE THREAD

**Issue by cst99003** [thomaschampagne/stravistix#516]
I am seeing triple versions of many things on the screen

1. The Fitness Trend droplist (note two are version 6.0.0 and one is 5.13.0)
2. The Show Extended Stats
3. Remote Views, Relive and Weather

I am using Chrome Version 63.0.3239.132

https://www.strava.com/athletes/190502

**Comment by thomaschampagne** [comment]
You probably tested v6.0.0 along side 5.13.0. Like written in install guide i provided to you https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive

>Disable the official StravistiX for Strava extension (if you use it in your chrome) to avoid any conflicts with the version you are installing now.
