### ISSUE TITLE
Multi-sport fitness trend not adding all activites

### ISSUE THREAD

**Issue by barfarina** [thomaschampagne/stravistix#517]
It keeps not adding activities to the multi-sport trend, which would otherwise be the most useful feature. This isn't limited to my account, but also to my wife's. For instance, I've done 4 cycling activities in the past 5 days, but the data import says I've only done 3 with 2 rest days - this will very obviously screw with the data and outcomes found (i'm coming back from a shoulder reconstruction, so my fitness is WAY down). 

This isn't an isolated incident - we both went cycling months ago and did big rides, but each of us lost a ride we expected to see (and so we were looking to see the data that came from it in the 'trend'). I can't check every one, but I can't imagine why there wouldn't be more missing over 500+ activities.

Also, as an aside, the auto-sync just won't work. I have to do it manually every time, despite it set at 1 hr. 5 days without a sync today.

Great otherwise!

**Comment by thomaschampagne** [comment]
Hi,
Are you sure to have heartrate data on them?

**Comment by barfarina** [comment]
Well I was (I use either a garmin edge + HRM or fenix 3 HR watch), but I think you've just described a problem I didn't even know I was having! The missing activities are missing HR data for some reason, so I at least understand why they don't snow up in the trend data. No fault of the extension, just my GPS devices playing up as usual (2 failed on me yesterday in the one ride...).

Thanks 👍 Can totally live with the sync issues anyway - no drama.
