### ISSUE TITLE
Add an option to include/exclude e-bike rides types in fitness trend

### ISSUE THREAD

**Issue by metacosm** [thomaschampagne/stravistix#521]
Fitness graph doesn't currently include e-bike rides. While the engine definitely helps, e-bike riding still has an impact over fatigue and fitness. :)

**Comment by thomaschampagne** [comment]
@metacosm Can you provide a backup of your history? Thanks

**Comment by metacosm** [comment]
@thomaschampagne is there a way to do so privately? Don't really want to expose my history publicly…

**Comment by thomaschampagne** [comment]
Sure email me at th.champagne@gmail.com

**Comment by thomaschampagne** [comment]
@metacosm i will bring that later in 6.1.0 with list of type of sports to include/exclude

**Comment by thomaschampagne** [comment]
@metacosm I will finally bring it earlier in v6.0.1 as "quick win" (fixing release of just released v6.0.0)

Toggle option like this
![image](https://user-images.githubusercontent.com/151973/36504216-0b8c03a0-1750-11e8-8a2b-e29207143e24.png)

**Comment by thomaschampagne** [comment]
@metacosm Will toggle icon seems legit for you?

Icon database: https://material.io/icons/

I identified "power" or "power settings new"

**Comment by metacosm** [comment]
@thomaschampagne power looks good, a little worried it might be confused with the other lightning icon, though

**Comment by thomaschampagne** [comment]
@metacosm you right. any other solution?

**Comment by thomaschampagne** [comment]
Also a tooltip text is displayed on mouse over icon

**Comment by metacosm** [comment]
I don't have a better idea, apart maybe, though it might look weird, `ev_station`

**Comment by thomaschampagne** [comment]
@metacosm Nice one ;) Also `battery charging full`

**Comment by thomaschampagne** [comment]
or `motorcycle`

**Comment by metacosm** [comment]
@thomaschampagne `battery charging full` might be best!

**Comment by thomaschampagne** [comment]
@metacosm Ready for 6.0.1 ;)

(je suis de Meylan ;))

**Comment by metacosm** [comment]
@thomaschampagne merci! 
(Et oui, je sais que tu es du coin! ^_^)

**Comment by thomaschampagne** [comment]
@metacosm Si jamais tu veux bien tester que tout est OK avant release finale, tu peux télécharger le dernier build de develop:

https://bintray.com/thomaschampagne/stravistix/travis-ci-builds/develop#files

Si bugs je ré ouvre le ticket.

Merci,

Tom

**Comment by metacosm** [comment]
@thomaschampagne everything looks good, just a quick UI nitpicking: it's difficult to quickly figure out which icon is associated with a checkbox: is it the one on the left or on the right? The fact that the icon is actually closer to the next checkbox than the one it is associated with is confusing.
Of course, by checking the whole sequence, you figure it out but clearer separation (maybe more space between each checkbox/icon pair) or visual association (box around each checkbox/icon pair) would help.
<img width="257" alt="screen shot 2018-02-25 at 17 48 42" src="https://user-images.githubusercontent.com/120057/36644067-2474a45a-1a55-11e8-8635-75c15c665323.png">

Maybe I should open a separate issue for this?

(retour à l'anglais pour la compréhension de tout le monde, même si je ne sais pas si tu as des contributeurs)

**Comment by thomaschampagne** [comment]
@metacosm Ok thanks i will handle that

**Comment by metacosm** [comment]
Weird because it was clearer on the screenshot you posted earlier…

**Comment by thomaschampagne** [comment]
@metacosm It depends of the window width size

**Comment by thomaschampagne** [comment]
@metacosm I fixed like this:
![image](https://user-images.githubusercontent.com/151973/36644605-f4e59548-1a5c-11e8-844a-bb8c37851144.png)
![image](https://user-images.githubusercontent.com/151973/36644612-016cad2e-1a5d-11e8-98ae-d4c951f435f3.png)

**30% & 70% width distribution**
