### ISSUE TITLE
garmin connect not working

### ISSUE THREAD

**Issue by billhoffman** [thomaschampagne/stravistix#524]
**Bug description:** 
garmin connect is no longer working for me
**Actual Behavior:** 
I see my run on the garmin site, but not on strava
**Expected Behavior:** 
Has been working for years, just stopped working
**Steps to Reproduce:** 
sync activity to garmin, and wait, nothing happens.
- ...
 - ...
 - ...

**Chrome version** 

**Plugin version:** 

**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by billhoffman** [comment]
Here is the last one that worked. https://www.strava.com/activities/1395979676

**Comment by thomaschampagne** [comment]
hi @billhoffman 
Not sure that's a stravistix bug ;) 

Does it works when stravistix is disabled? unlink/relink your garmin acccount to strava ;)

**Comment by billhoffman** [comment]
Duh!  Meant to report to strava itself...   Sorry, thanks, and sorry for the noise.

**Comment by thomaschampagne** [comment]
No problem ;)
