### ISSUE TITLE
Year progression in imperial units and metric

### ISSUE THREAD

**Issue by kleinen12** [thomaschampagne/stravistix#527]
There does not seem to be a way to change the yearly progression data from metric to imperial units.  Also is there a better way to display the progression year data. 

metric data only

ability to change to empirical units for the yearly progression data

Go to Year Progressions and click the "select data" dropdown".  All of the choices are in metric - it would be nice to also see empirical units.

lates
not sure

``` 
put console errors here if exist 
``` 

**Link screenshots or youtube video link if necessary:**

**Comment by thomaschampagne** [comment]
Problem will be fixed in v6 ;)
