### ISSUE TITLE
Remove old app (options/)

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#531]

**Comment by beyond-code-github** [comment]
Hi @thomaschampagne, hope you are well! I don't know if this is the right place to ask, but do you have plans to bring the new fitness trend graph up to match the old one? It's not a major thing but I am currently still finding myself using the old one for the following reasons:

Layour is nicer and more clear (new one has less space etc)
Options checkboxes are not as nice
Don't get the dotted lines that show me where each threshold starts/ends.
Lines themselves are quite thin and don't stand out from the graph background
Vertical lines that align with activities are a bit confusing, old version with time based vertical lines was better as it matches the axis.

I know some of this is subjective, but I thought you'd appreciate the feedback all the same. I'm happy to try send some PRs if that would help.

Keep up the great work!

**Comment by thomaschampagne** [comment]
@beyond-code-github We can talk about this here ;) no problem
You right about the final rendering of the new graph. I'm doing lot of changes from users feedback including yours.

Current changes as today on develop:

![image](https://user-images.githubusercontent.com/151973/37202171-0a2cdebc-238a-11e8-880c-029e99f5a950.png)

**Done:** I removed verticals lines. Added active days dotted line on Y = 0.  Implemented a tooltip system like previous one.

**To be done**: Form filled area back. And colored or more visible training zones. Other?

You can test the latest develop build here: https://bintray.com/thomaschampagne/stravistix/travis-ci-builds/develop#files/ (Install guide: https://github.com/thomaschampagne/stravistix/wiki/How-to-install-stravistix-build-archive)

I would like to have your feedback if possible until you're happy !

The old version is still available to handle situation like this with you :). I'll remove old version when users are all satisfied with the new one.

Tom

**Comment by beyond-code-github** [comment]
Thanks @thomaschampagne! That definitely looks like it goes a long way to bridging the gap. I think your list covers everything, although it still could be worth making the series lines one or two pixels thicker I reckon.

Happy to keep weighing in though, always willing to lend on opinion if you need it. Keep up the great work!

**Comment by thomaschampagne** [comment]
@beyond-code-github What are "the series lines" ?!

**Comment by thomaschampagne** [comment]
New update:
![capture](https://user-images.githubusercontent.com/151973/37220152-fc23dcbc-23c5-11e8-8252-87424b2d46b7.JPG)

**Comment by beyond-code-github** [comment]
Ahhh the series lines are the data plots in the graph, as opposed to the grid lines, so the purple/yellow/orange ones
