### ISSUE TITLE
Year Progression (new)

### ISSUE THREAD

**Issue by jcaude** [thomaschampagne/stravistix#533]
### Feature Requests

Besides the [delta prev year] it would be nice to have a [delta 2018 year] to compare the current season or year to all precedents seasons .. for example to know how many km more or less I have done until now compared to 2015 (see mockup below)

![capture d ecran 2018-02-22 a 15 09 54](https://user-images.githubusercontent.com/1268176/36543371-e57ab5dc-17e3-11e8-80a8-16588785f729.png)

```typescript
import { DeltaType } from "./delta-type.enum";

export class DeltaValue {
	public deltaType: DeltaType;
	public deltaSignSymbol: string;
	public deltaClass: string;
}

export class ProgressionAtDayRow {
	public year: number;
	public color: string;
	public previousDate: string;
	public progressTypeLabel: string;
	public progressTypeUnit: string;
	public currentValue: number;
	public deltaPreviousYear: DeltaValue;
	public deltaCurrentYear: DeltaValue;
}
```

**Comment by jcaude** [comment]
Thanks thomas.. I really do appreciate the new feature.

**Comment by thomaschampagne** [comment]
You are welcome ;)
