### ISSUE TITLE
Incorrect explanation on PSS doc

### ISSUE THREAD

**Issue by bizzehdee** [thomaschampagne/stravistix#535]
* Plugin version: 6.0.0 Stable
  * Angular version: 5.2.3
  * D3js version: 4.13.0
  * Chrome/Opera/Chromium version: Chrome 64
  * OS version: Win10
  
In the documentation for Power Stress Score (PSS), the method is described as:

`PSS = ((EffortInSeconds * WeightedPower * Intensity) / AverageWatts) * 100`

The actual method used in the code to calculate PSS is

`PSS = ((EffortInSeconds * WeightedPower * Intensity) / (FTP * 3600)) * 100`

The method described gives wildly inaccurate PSS scores compared to the actual method.

![pss](https://user-images.githubusercontent.com/3287555/36595171-11f80280-1899-11e8-962d-6c9e5f965de5.png)

**Comment by thomaschampagne** [comment]
@bizzehdee Thanks ! Fixed for next released !
