### ISSUE TITLE
Activity Feed Auto-Scroll Occasionally Not Working

### ISSUE THREAD

**Issue by KylePolansky** [thomaschampagne/stravistix#536]
* Plugin version: 6.0.1 Stable
  * Chrome/Opera/Chromium version: Chrome 64.0.3282.186 (also happens on another computer running Chrome 63.0.3239.132)
  * OS version: Windows 10
  
#### Steps to reproduce:

  1. Scroll down activity feed (https://www.strava.com/dashboard/)
  2. Occasionally auto-scroll fails and the "More" button appears. This appears to be random, but is often on the first page load (https://www.strava.com/dashboard/following/) and when the url is (https://www.strava.com/dashboard/following/90)
  3. Note: Have tried in incognito mode (with the plugin enabled), disabling all other plugins, and using another computer. Auto-Scrolling works correctly when disabling the plugin.
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
No install or update detected
localStorageMustBeCleared is now true
A previous sync exists on Fri Mar 02 2018 01:43:36 GMT-0600 (Central Standard Time)
Do not auto-sync. Last sync done under than 60 minute(s) ago
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
The feed should auto-scroll until reaching the end without having to click the "more" button.

  
#### Media attachement:

>You can upload/attach any images to this ticket.

[2018-03-02 01_50_58-dashboard _ strava](https://user-images.githubusercontent.com/6778740/36888687-34e2aa66-1dbc-11e8-8656-6d7deecc69b2.png)

#### Providing your stravistix synced athlete history can be usefull to solve the problem

> To export you history click on "sync button" (top right and corner), then "Backup history". You can zip the file and upload it here. 

[2018.3.2-1.41_v6.0.1.history.zip](https://github.com/thomaschampagne/stravistix/files/1774134/2018.3.2-1.41_v6.0.1.history.zip)

**Comment by thomaschampagne** [comment]
I were not able to reproduce this. Still experiencing it? I let you close the ticket or not.

Ty
