### ISSUE TITLE
Fatigue toggle on/off in fitness trend plot

### ISSUE THREAD

**Issue by maartenmennes** [thomaschampagne/stravistix#540]
Feature request: ability to turn off Fatigue in the Fitness trend plot. Given that we have both fitness and form, there is no need to display fatigue. Being able to toggle it on/off would be very useful and clean up the graph nicely.

**Comment by thomaschampagne** [comment]
@maartenmennes Thanks for reporting this.

I will not dive into at the moment since i have too many work at the moment. I mark this as "easy". Maybe someone else will do it. Or me later.

**Comment by Devel42** [comment]
A toggle for all those hundreds of vertical lines would be good too. They really clutter up the graph, I prefer the old one. A big thanks for all your hard work though!

**Comment by thomaschampagne** [comment]
@Devel42 I may drop vertical lines on next patch following various feedback including yours ;) I'm doing 
 visuals changes to the graph to make it more clear (E.g. tooltip are coming back on next patch)

Even it's not the purpose of this ticket, could you detail me why "prefer the old one"? It helps me to adjust things ;). My goal is to switch on the new version without having unhappy users :) Thx !

**Comment by Devel42** [comment]
Many thanks Thomas, the new graph is much clearer (and a bit like the old one :) ). It would still be good to have more switches for fatigue, form etc, but what I like especially are the zones - freshness, neutral, optimal etc. What would be really nice is to have them with different coloured backgrounds. Right now it is a little confusing as to what is above or below the lines.
