### ISSUE TITLE
Add some more horizontal lines on graph

### ISSUE THREAD

**Issue by saxmund** [thomaschampagne/stravistix#543]
Feature request: I find the fitness line looks flat, compared with the fatigue line which is much more variable. It is hard to see how fitness is increasing, mine just looks like it wiggles up and down. Some horizontal lines on the graph would guide the eye, just as you have them at specific values for the form line

**Comment by thomaschampagne** [comment]
Like this?
![image](https://user-images.githubusercontent.com/151973/37300363-13b4e206-2626-11e8-8482-849e1b518697.png)
![image](https://user-images.githubusercontent.com/151973/37300449-49b78d86-2626-11e8-9489-5b04747d776e.png)

.. But it might create confusion i would like to remove when training zones are activated like this:

![image](https://user-images.githubusercontent.com/151973/37300632-b8d7a994-2626-11e8-8d62-1ff80f918567.png)

**Comment by saxmund** [comment]
Yes, just like that. It gives some scaling to the fitness line. I think showing the training zones as a heavier dashed line does remove the possible confusion.

It's looking good, by the way, initially I preferred the old format but your recent update improves it a lot.

Phil
