### ISSUE TITLE
Vertical position of graph in new fitness trend is not static

### ISSUE THREAD

**Issue by stupid-beard** [thomaschampagne/stravistix#544]
In 6.0.2 stable, if you have a day with multiple activities or activities with a long title, the vertical position of the graph is pushed down when mousing over a day. This is because the list of activities in the top right wraps causing it to use a variable number of lines.

This means that when you move the mouse over the graph it jumps around a lot and is very jarring. I'd suggest you either truncate the list of activities or show them elsewhere. Perhaps below the graph or in the new mouse over pop up thingy.

Hopefully this is clear, if not let me know and I'll take some screenshots.

**Comment by thomaschampagne** [comment]
@stupid-beard I see what's going wrong. i limite the displayed activities to 2. I will truncate full text with ellipsis
