### ISSUE TITLE
fitness trend does not read stress scores for all activities

### ISSUE THREAD

**Issue by motorthings** [thomaschampagne/stravistix#547]
After a full sync, the new 6.0.2 build shows activities through the present, but does not have any stress scores for events past January 12, 2018. This means the fitness trend just tapers away to nothing after that date, though the events are listed, and include power data.

The old app shows the same activities WITH stress scores, and a correct fitness trend.

Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Windows 10 
  
No errors in developer console and javascript logs

[2018.3.13-16.03_v6.0.2.history.zip](https://github.com/thomaschampagne/stravistix/files/1808807/2018.3.13-16.03_v6.0.2.history.zip)

**Comment by thomaschampagne** [comment]
Did you read the FAQ? 😄 😄

As written in the FAQ https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions#im-not-seeing-some-activities-after-a-sync-re-sync-or-auto-sync

>This fitness trend is "Multi-sports" oriented as long as you hold a heart rate monitor and/or cycling power meter and/or swimming activities having distance & time.

So no stress score when workout has no HRM/Power meter (expect for swiming)

On old app these activities are not displayed. On new app they are to get less confusion. Even if no stress score can be calculated on them.

So, it's a normal behavior :)

**Comment by motorthings** [comment]
I did read the FAQ, actually...The activities that do not show up DO include power data.

**Comment by motorthings** [comment]
I added a new comment to the issue, but am not sure if it will re-open the
issue or not....

On Wed, Mar 14, 2018 at 11:45 AM, Thomas Champagne <notifications@github.com

**Comment by thomaschampagne** [comment]
Ticket isn't re opened. The behavior is normal. I tested your backup.

**Comment by motorthings** [comment]
I don't get how it is "normal" when the power data exists, and it the
fitness trend picks up the power data from the same activities in the old
version...what am I missing?

thanks,
charlie

On Wed, Mar 14, 2018 at 12:45 PM, Thomas Champagne <notifications@github.com
> wrote:

> Ticket isn't re opened. The behavior is normal. I tested your backup.
>

**Comment by thomaschampagne** [comment]
Ok i reopen. So my bad :/ Do you have an activity id which must have stress score and have to be seen as impulse in fitness graph? 

Thanks

Tom

**Comment by motorthings** [comment]
Tom,

No worries....any of the activities in the last two weeks should have power
data (all of them but 1 or 2 since Jan 12th should have power data).
I'm not sure how to get you an activity ID, though?

Thanks,
Charlie

**Comment by thomaschampagne** [comment]
Just open them in Strava. And copy paste links here ;)

**Comment by motorthings** [comment]
https://www.strava.com/activities/1451397683
https://www.strava.com/activities/1448467683
https://www.strava.com/activities/1446453750

**Comment by thomaschampagne** [comment]
It works on my side. I can see you last 3 activities on the graph with your backup :/
![image](https://user-images.githubusercontent.com/151973/37436300-90a35cf8-27e7-11e8-8627-0d28637c70e1.png)

**Comment by motorthings** [comment]
what else do you suggest I do besides a full sync?

thanks,
charlie

**Comment by thomaschampagne** [comment]
Yes try this. But before press F12 to open developer console and copy paste any errors you see in console. That could help me. What do you see exactly? Do you have a screenshot?

**Comment by motorthings** [comment]
before full sync:


after clearing full local history and doing a full re-sync:


going back to old app:

**Comment by thomaschampagne** [comment]
@motorthings You may have put screenshots through email.

Can't see them on github. Could reply post screens from here: https://github.com/thomaschampagne/stravistix/issues/547 directly

Thx

Tom

**Comment by thomaschampagne** [comment]
:) just activate power meter by clicking that: 

![image](https://user-images.githubusercontent.com/151973/37466967-4a6428bc-285f-11e8-90c7-4eb2cd342e6e.png)

And you're done.

**Comment by motorthings** [comment]
i am an idiot...i expected it to be on by default like on the old version.
i appreciate your time, and will make a donation to fund your time spent on
stupid issues like mine.

charlie

**Comment by thomaschampagne** [comment]
Don't worry charlie ;) I assume that i can close this from now :smile: :smile:

**Comment by motorthings** [comment]
yes, and thanks again for your attention.

**Comment by thomaschampagne** [comment]
@motorthings Thanks for your gesture :) You will receive from me  a "real thanks" message later ;) (I usually give more info on what is going on the plugin in this kind of mail :))
