### ISSUE TITLE
Fitness Trend page stuck in "loading" state

### ISSUE THREAD

**Issue by dee-see** [thomaschampagne/stravistix#548]
### Step 2: Describe your environment

  * Plugin version: 6.0.2 Stable
  * Chrome/Opera/Chromium version: Chromium 65.0.3325.162 (Developer Build) (64-bit)
  * OS version: Arch Linux, 4.15.8 kernel
  
### Step 3: Describe the problem:

I don't have whatever is required to calculate fitness data and the page is forever stuck in loading mode.

#### Steps to reproduce:

  1. Open the fitness tab

#### Actual Behavior:

The "loading" indicator stays on screen forever with the following message in the console:

  ```javascript
0.5b569a3e3a20ec953891.chunk.js:1 No activities has minimum required data to generate a fitness trend
(anonymous) @ 0.5b569a3e3a20ec953891.chunk.js:1
t.invoke @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
onInvoke @ main.848fdb43d2c619ccee5f.bundle.js:1
t.invoke @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
e.run @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
(anonymous) @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
t.invokeTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
onInvokeTask @ main.848fdb43d2c619ccee5f.bundle.js:1
t.invokeTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
e.runTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
d @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
Promise.then (async)
v @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
t.scheduleTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
onScheduleTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
t.scheduleTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
e.scheduleTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
e.scheduleMicroTask @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
P @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
S @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
(anonymous) @ polyfills.967fe5e6c57e15a99b6d.bundle.js:1
(anonymous) @ main.848fdb43d2c619ccee5f.bundle.js:1
safeCallbackApply @ extensions::uncaught_exception_handler:27
handleResponse @ extensions::sendRequest:67

  ```
  
#### Expected Behavior:

Empty graph/table, ideally with a message saying why.

**Comment by thomaschampagne** [comment]
@dee-see Could you provide me a backup of your history?
So i can reproduce and fix your problem. Thanks !

**Comment by dee-see** [comment]
@thomaschampagne  https://www.dropbox.com/s/dmk8z74m6k8b4lv/2018.3.16-12.13_v6.0.2.history.json?dl=0

Let me know when you picked it up please, I will delete the file.

**Comment by thomaschampagne** [comment]
@dee-see You can remove your link.

The bug is that there is no good displayed message for your case.

In fact, your history is not supported by this feature:

The fitness trend requires an athlete history with at least:

- Heart rate data coming from an heart rate monitor and regardless types of sports.
- Or power data coming a cycling power meter (or emulated power data such as "ZWIFT" sessions).
- Or any swimming activities having distance & time (no sensors required). For this make sure you have set your Swimming Functional Threshold Pace in athlete settings.

Hope this helps,

Tom
