### ISSUE TITLE
Possible to get API from Stravistix?

### ISSUE THREAD

**Issue by ekosynth** [thomaschampagne/stravistix#550]
Hi, I was wondering if it's possible to get an API from Stravistix for the Fitness Trend graph? I'd like to build a combined view of this against my weight loss from Fitbit.

**Comment by thomaschampagne** [comment]
It's local to your browser. You can get data with:

```
chrome.storage.local.get((d) => {
     console.log(d);
});
```

**Comment by ekosynth** [comment]
Hmm. This is doesn't seem to work in Chrome console. The only things I see in a local storage are a couple of parameters for the fitness trend graph like fitnessTrend_EBikeRidesEnabled.

**Comment by thomaschampagne** [comment]
Strange. Is your history synced?
