### ISSUE TITLE
Year Progression (new) overview

### ISSUE THREAD

**Issue by rreijers** [thomaschampagne/stravistix#553]
In the Year Progession overview in the new app, it only shows the delta for a given Progress type, like distance, count, elevation or time. 
![image](https://user-images.githubusercontent.com/19285907/37699348-6c82f0f4-2ce7-11e8-94c8-114b616e4d70.png)

In the old version, a total overview of all Progress types was shown for the current date.

![image](https://user-images.githubusercontent.com/19285907/37699307-48d511c8-2ce7-11e8-8ba7-6f08b78ee8a4.png)

Is it possible to get this overview back?

**Comment by thomaschampagne** [comment]
Does this feedback related to https://github.com/thomaschampagne/stravistix/issues/533?

**Comment by rreijers** [comment]
No, it doesn't. In the old app there was an overview of all aspects of progress, compared to the previous year. Now I have to select the progress type and get the overview of that progress type (eg distance) and have to click again on a progress type to get that overview.

**Comment by thomaschampagne** [comment]
Your ticket has been closed :) . Could test/validate that everything is OK using latest generated build from https://bitbucket.org/thomaschampagne/stravistix-ci-builds/downloads/ ?

If you don't approve the test build, you can reopen this ticket :)

**Comment by rreijers** [comment]
@thomaschampagne Thanks a lot for adding this overview again in the new app! Really happy!
