### ISSUE TITLE
Heart Rate Zones Not Being Reported Accurately

### ISSUE THREAD

**Issue by brianjmull** [thomaschampagne/stravistix#555]
I just installed Stravistix (Version 6.0.3) today for the first time on an updated version of Chrome (Version 65.0.3325.181) on a Mac running 10.13.3.

From what I can see, everything that I'm looking at seems to be getting reported accurately except for heart rate. I've attached two images below. One is from Zwiftpower and the other is from Stravistix. The Zwiftpower chart by far is the accurate report. My average heart rate for the ride was 173.

Thanks for taking a look.

<img width="1307" alt="screen shot 2018-03-24 at 5 54 41 pm" src="https://user-images.githubusercontent.com/37756091/37869886-bb15c490-2f8e-11e8-92f7-4a4577e0f3bb.png">
<img width="1326" alt="screen shot 2018-03-24 at 6 05 41 pm" src="https://user-images.githubusercontent.com/37756091/37869887-bfd0ece4-2f8e-11e8-8b13-2ceb2bfa8806.png">

**Comment by thomaschampagne** [comment]
Strange.

Can you press F12 and type in console:
localStorage.clear()

Then reload.

Activity link?

Thanks

**Comment by brianjmull** [comment]
That fixed it. Thanks again.
