### ISSUE TITLE
Suggestion: discount factor for non-power meter results

### ISSUE THREAD

**Issue by dbwz8** [thomaschampagne/stravistix#556]
* Plugin version: 6.03
  * Chrome/Opera/Chromium version: Chrome 6.5
  * OS version: Windows 10
  
### Step 3: Describe the problem:

Just a suggestion; Any activity I do without a power meter always comes up way to high on the stress score (comparatively) . It would be nice in the Athlete Settings if you could specify a discount multiplier (e.g., 0.85) for non-power meter activities. Thanks!

**Comment by jayti74** [comment]
Hi @dbwz8 this is already adressed here: #341 and ready to be tested!

**Comment by dbwz8** [comment]
Sorry. Missed it.
