### ISSUE TITLE
Zone Settings: Default Zones Calculation (Cycling Power)

### ISSUE THREAD

**Issue by jayti74** [thomaschampagne/stravistix#557]
1: why are there 50 cycling power zones at the standard config. i only know 6 or 8 powerzone approaches (Coggan (6), Durata (8), USAT (6)) unpleasant to remove 44 of them, by clicking the 'x'.
![50powerzones](https://user-images.githubusercontent.com/33221550/37966184-f8a1c512-31c7-11e8-9227-5378bab1852f.PNG)

 
2: feature request: automated power zones default calculation based on ftp would be really nice. Coggans approach would be a common zone calculation method. (https://www.trainingpeaks.com/blog/power-training-levels/) 
Zone 1: <55% FTP
Zone 2: 56-75% FTP
Zone 3: 76-90% FTP
Zone 4: 91-105% FTP
Zone 5: 106-120% FTP
Zone 6: >121% FTP

(Would also be nice to have for Heart Rate Zone Setting...)

**Comment by thomaschampagne** [comment]
@jayti74 understood.

I could reduce default zones to 8 zones as a "quick win" first?

Later your request  could be processed.

**Comment by jayti74** [comment]
@thomaschampagne default to 8 sounds good :) thanks
