### ISSUE TITLE
Track and manage athlete settings changes over time

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#563]

**Comment by kuba-wu** [comment]
Please correct me if I'm wrong but I assume that this should include changes in TSS / TRIMP / HRSS calculation so that time-bounded athlete settings (FTP etc.) are reflected, right?

**Comment by thomaschampagne** [comment]
Exactly. Get the right weight, hr, ftp,... for the calculation of an
activity at a given date with the physical settings you had on that date.



On Apr 11, 2018 9:54 PM, "Kuba Wach" <notifications@github.com> wrote:

Please correct me if I'm wrong but I assume that this should include
changes in TSS / TRIMP / HRSS calculation so that time-bounded athlete
settings (FTP etc.) are reflected, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/thomaschampagne/stravistix/issues/563#issuecomment-380575780>,
or mute the thread

**Comment by kuba-wu** [comment]
Great, I was just about to file an enhancement request for this. I'd like to volunteer for the task then. I have no experience with Stravistix source code but few years in Angular.js and Angular, so will need some time to get up to speed but should be rather productive after. What do you think?

**Comment by jlhuertas** [comment]
This would be a very useful feature. I've had significant changes in my FTP over the last few months and if I use the current one it will underestimate the old rides but if I keep a previous FTP it is overestimating my current efforts.

**Comment by thomaschampagne** [comment]
Feature is live: closed by #625
