### ISSUE TITLE
FTP calculation should be 0,95 of the 20-min max power

### ISSUE THREAD

**Issue by puzanart** [thomaschampagne/stravistix#565]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/stravistix/issues?

### Step 2: Describe your environment

  * Plugin version: 6.1.0 Stable
  * Chrome/Opera/Chromium version: Version 65.0.3325.181 (Official Build) (64-bit)
  * OS version: Windows 10 Pro
  
### Step 3: Describe the problem:
Recently you added the FTP to every ride, but it's equal to 20-min max power which is not correct. It should be down 5% of the 20-min test.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete history can be usefull to solve the problem

> To export you history click on "sync button" (top right and corner), then "Backup history". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
- [ ] Change FTP helper in athlete settings
