### ISSUE TITLE
Can't sync my data.

### ISSUE THREAD

**Issue by machadocosta** [thomaschampagne/stravistix#566]
**Bug description:** 
Crash on synchronization.
**Actual Behavior:** 
The app crashes when processing activities at 8%. Chrome shows the "Aw, Snap!" window.
**Expected Behavior:** 
It should not crash and update my data...
**Steps to Reproduce:** 
- happens every time I hit the command "sync" and "redo full sync"

**Chrome version** 
Version 65.0.3325.181 (Official Build) (64-bit)
**Plugin version:** 
Plugin version: 6.1.0 Stable and also happens when I switch to "the old app".
**Activities links?:** 

**Console errors? (press F12 to see developer console, and copy paste here):** 
static.ads-twitter.com/oct.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/?file=gdata&v=1.x, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22
2jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/api/gdata/1.10/208a907929e7936990d2bf48205aa8d8/core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22
(anonymous) @ ?file=gdata&v=1.x:8
9Error: <svg> attribute width: A negative value is not valid. ("-32")
9Error: <rect> attribute width: A negative value is not valid. ("-32")
jquery-3.2.1.min.js:3 The specified value "hide" is not a valid number. The value must match to the following regular expression: -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)?
qa @ jquery-3.2.1.min.js:3
Ja @ jquery-3.2.1.min.js:3
after @ jquery-3.2.1.min.js:3
(anonymous) @ stravini.js:254
j @ jquery-3.2.1.min.js:2
k @ jquery-3.2.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
fire @ jquery-3.2.1.min.js:2
i @ jquery-3.2.1.min.js:2
fireWith @ jquery-3.2.1.min.js:2
ready @ jquery-3.2.1.min.js:2
S @ jquery-3.2.1.min.js:3
manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2 Uncaught TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at e.handleDomElementRemoved (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at Mb.j (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
e.handleDomElementRemoved @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.handleDomMutations @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
StravistiX.js:164 Skip handlePluginInstallOrUpgrade since we are on a sync
StravistiX.js:707 Sync Popup. Skip handleOnFlyActivitiesSync()
manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2 Uncaught TypeError: Failed to execute 'unobserve' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at e.handleDomElementRemoved (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at Mb.j (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
    at e.walkNodeTree (manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2)
    at e.Mb.j [as walkNodeTree] (core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8)
e.handleDomElementRemoved @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.walkNodeTree @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
e.handleDomMutations @ manifest-037a41114938848511060c98235d688204e1f936db39c371d7f1259ad38690b8.js:2
Mb.j @ core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js:8
MenuModifier.js:38 PositionError {code: 1, message: "User denied Geolocation"}
(anonymous) @ MenuModifier.js:38
ActivitiesSynchronizer.js:176 [PagesRidden] Resolving with 40 activities found
ActivitiesSynchronizer.js:81 Activities fetched in group [1 => 2]: 40
ActivitiesSynchronizer.js:95 Stream length: 0, raw activities length: 40)
ActivitiesSynchronizer.js:292 Group handled count: 1
ActivitiesSynchronizer.js:322 Group [1 => 2] handled
ActivitiesSynchronizer.js:176 [PagesRidden] Resolving with 40 activities found
ActivitiesSynchronizer.js:81 Activities fetched in group [3 => 4]: 40
ActivitiesSynchronizer.js:95 Stream length: 40, raw activities length: 40)
chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:354 No ftp available for this range
ActivityComputer.powerData @ chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:354
ActivityComputer.computeAnalysisData @ chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:88
ActivityComputer.compute @ chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:26
(anonymous) @ dbbb9eec-3da4-40d6-807f-810e1502fa22:14
Promise.then (async)
onmessage @ dbbb9eec-3da4-40d6-807f-810e1502fa22:12
chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:422 No fthr available for this range
ActivityComputer.heartRateData @ chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:422
ActivityComputer.computeAnalysisData @ chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:90
ActivityComputer.compute @ chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/core/scripts/processors/ActivityComputer.js:26
(anonymous) @ dbbb9eec-3da4-40d6-807f-810e1502fa22:14
Promise.then (async)
onmessage @ dbbb9eec-3da4-40d6-807f-810e1502fa22:12
```

**Comment by thomaschampagne** [comment]
Could you test  that build?
https://bitbucket.org/thomaschampagne/stravistix-ci-builds/downloads/v6.1.0_stable_2018-04-04-21-33.develop.990e432c.zip

And tell me if sync pass?

Thanks !

**Comment by machadocosta** [comment]
It works!

Thanks a lot for your work!

**Comment by thomaschampagne** [comment]
You're welcome.

It will be available in 6.1.1. I may release it end of week.

Tom

**Comment by thomaschampagne** [comment]
Fixed with: https://github.com/thomaschampagne/stravistix/commit/990e432cce797387cf01383443e108749a6a6193
