### ISSUE TITLE
Can't mark "Don't show this message again" or click "Got it"

### ISSUE THREAD

**Issue by lindomaroliveira** [thomaschampagne/stravistix#571]
Plugin version: 6.1.1 Stable
Angular Core version: 5.2.9
Angular Material version: 5.2.4
D3js version: 4.13.0

Chrome: Versão 65.0.3325.181 64 bits
OS: Windows 8.1
  
### Step 3: Describe the problem:
When I open the plugin and choose "Fitness Trend", it shows the window "Notice: improved fitness trend accuracy with a heart rate monitor."

But I'm unable to mark the option "Don't show this message again" or click "Got it" and the app got stuck.

I can use tab and change to other app section but can't dismiss the notice window.

**Comment by thomaschampagne** [comment]
@lindomaroliveira Thanks for reporting it.

If you press F12 to see developer console. To you see and error? Thanks.

If yes could you reproduce the problem with that debug build: https://bitbucket.org/thomaschampagne/stravistix-ci-builds/downloads/v6.1.1_stable_2018-04-10-16-52.develop.57d6d8f7.zip

Still press F12 :) And provide me the error? 

Thx for ur help !

**Comment by lindomaroliveira** [comment]
Hi,

I've installed the debug build and this is the log.

[cidpfgojdamhhhfjifdofcmjipfkpgeo-1523391764288.log](https://github.com/thomaschampagne/stravistix/files/1896310/cidpfgojdamhhhfjifdofcmjipfkpgeo-1523391764288.log)

**Comment by thomaschampagne** [comment]
My bad i didn't linked a debug build, but a release one :/

Can you retry with below build?

[v6.1.1_stable_2018-04-11-10-08.zip](https://github.com/thomaschampagne/stravistix/files/1898326/v6.1.1_stable_2018-04-11-10-08.zip)

Sry !

**Comment by lindomaroliveira** [comment]
Hi,

Here is the log!

[iofgclnjmbaehjecgieogppjcmbocffp-1523453839017.log](https://github.com/thomaschampagne/stravistix/files/1899039/iofgclnjmbaehjecgieogppjcmbocffp-1523453839017.log)

**Comment by lindomaroliveira** [comment]
Any workaround I can make to hide the message?

**Comment by thomaschampagne** [comment]
@lindomaroliveira Could you also provide me an export of your history from the toolbar? I need that to reproduce your bug.

As workaround on the app until next patch, enter this in your developer console:

`localStorage.setItem("fitnessTrend_hideWelcomeDialog", "true")`

The dialog will not be displayed anymore ;)

**Comment by lindomaroliveira** [comment]
I found the backup history option. Here is the file.

[2018.4.12-16.30_v6.1.1.history.json.log](https://github.com/thomaschampagne/stravistix/files/1904684/2018.4.12-16.30_v6.1.1.history.json.log)

**Comment by thomaschampagne** [comment]
Your ticket has been closed :) . Could test/validate that everything is OK using latest generated build from https://bitbucket.org/thomaschampagne/stravistix-ci-builds/downloads/ ?

If you don't approve the test build, you can reopen this ticket :)

**Comment by lindomaroliveira** [comment]
Worked !!!

Thanks for the fast solution!
