### ISSUE TITLE
Highest 20 minute average heart rate is incorrectly labelled as "Functional Threshold Heart Rate"

### ISSUE THREAD

**Issue by steveshort455** [thomaschampagne/stravistix#572]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/stravistix/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: Version 65.0.3325.181
  * OS version: _____
  
#### Steps to reproduce:

  1. View activity
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
The highest 20 minute heart rate is displayed as "Functional Threshold Heart Rate" but this is not correct as Functional Threshold Heart Rate (for one hour) is approximately 5% less than the highest heart rate achievable in 20 minutes.

  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
The highest 20 minute heart rate in the activity may be used to estimate Functional Threshold Heart Rate by reducing the 20 minute value by 5%. This is described in Joe Friel's "Fast After Fifty" book on page 148:

"The 20 minute test may be used to estimate your Functional Threshold Power (FTPo) or Functional Threshold Pace (FTPa). For FTPo, subtract 5% from your Normalized Power for the test. For FPTa, convert pace to speed by dividing 60 by your average 1-mile pace for the test. Again, subtract 5 percent to estimate FTPa. **In a similar manner, you can get a good approximation of your lactate-threshold heart rate by subtracting 5 percent from your average heart rate for the 20 minutes.**"
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete history can be usefull to solve the problem

> To export you history click on "sync button" (top right and corner), then "Backup history". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
Your ticket has been closed :) . Could test/validate that everything is OK using latest generated build from https://bitbucket.org/thomaschampagne/stravistix-ci-builds/downloads/ ?

If you don't approve the test build, you can reopen this ticket :)

**Comment by steveshort455** [comment]
Confirmed fixed. Many thanks.
