### ISSUE TITLE
Weight in STRAVA and Plugin are difrent

### ISSUE THREAD

**Issue by Gren69** [thomaschampagne/stravistix#577]
### Step 1: Are you in the right place?

  * Your problem may have been already covered in the FAQ. Did you check https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions?
  * Your problem or feature request may already exists in project issues section. Did you check https://github.com/thomaschampagne/stravistix/issues?

### Step 2: Describe your environment

  * Plugin version: _____
  * Chrome/Opera/Chromium version: _____
  * OS version: _____
  
### Step 3: Describe the problem:

Weight in STRAVA and Plugin are difrent 
[Screen1](https://www.dropbox.com/s/2p3e3dkts4mvud5/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-04-19%2013.47.16.png?dl=0)

[Screen2](https://www.dropbox.com/s/jjzkaejeffe10ng/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202018-04-19%2013.47.26.png?dl=0)

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete history can be usefull to solve the problem

> To export you history click on "sync button" (top right and corner), then "Backup history". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
Indeed :) You have to change the value by yourself in stravistix. An auto-sync is planned by the way.

**Comment by Gren69** [comment]
Understood :)

Владимир Григоренко 
......
