### ISSUE TITLE
Profile images not loading & goals show html.

### ISSUE THREAD

**Issue by rhysisterix** [thomaschampagne/stravistix#585]
Environment:

  * Plugin version 6.1.2 (Stable)
  * Chrome Version 66.0.3359.117 (Official Build) (64-bit)
  * OS High Sierra 10.13.4
  
Problem:

Newsfeed/main page

<img width="1207" alt="screen shot 2018-04-28 at 21 01 59" src="https://user-images.githubusercontent.com/1313539/39399981-c7fc80fe-4b27-11e8-8f82-a5edc5680f9e.png">

Profile images do not load (this happens in many places including Flyby's and seems to not affect all profiles - just some of them). At the same time the "goals' on the left-hand side show html instead of just the test. 

I have tested in incognito mode without the plugin and it works fine so this is definitely the plugin.
  
#### Actual Behavior:

I can see the error: Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
static.ads-twitter.com/oct.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
stats.g.doubleclick.net/r/collect?t=dc&aip=1&_r=3&v=1&_v=j67&tid=UA-6309847-24&cid=794550172.1519937905&jid=825369902&gjid=592732968&_gid=965968610.1524465657&_u=SCCAgAAL~&z=2119944405:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.link/_r?sdk=web2.33.1&branch_key=key_live_lmpPsfj2DP8CflI4rmzfiemerte7sgwm&callback=branch_callback__0:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM1299 dashboard:8880 Error: Branch SDK initialization failed, so further methods cannot be called
 Failure Code:Request blocked by client, probably adblock
    at Array.<anonymous> (branch-latest.min.js:106)
    at a (branch-latest.min.js:10)
    at Z.X (branch-latest.min.js:10)
    at Z.link (branch-latest.min.js:106)
    at Object.createLink (VM1231 dashboard:271)
    at VM1299 dashboard:8875
2jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/?file=gdata&v=1.x, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22
2jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22 A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/api/gdata/1.10/208a907929e7936990d2bf48205aa8d8/core,mediarss,geo,opensearch,atom,threading,app,gdata,finance,contacts,analytics,blogger,maps,gbase,acl,calendar,default.I.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
google.loader.f @ jsapi?key=ABQIAAAA9S76sdh5KSPpfr65zxQHGBT-rU0CFRjazioGWeeHjJLEyYXO2RSmaFbEdGganPrQRY2l3ORmYrTPpA:22
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.link/_r?sdk=web2.33.1&branch_key=key_live_lmpPsfj2DP8CflI4rmzfiemerte7sgwm&callback=branch_callback__1:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
StravistiX.js:211 No install or update detected
StravistiX.js:70 localStorageMustBeCleared is now true
stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-51167057-4&cid=794550172.1519937905&jid=733708937&_gid=965968610.1524465657&gjid=528785214&_v=j67&z=1643169486:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
app.link/_r?sdk=web2.33.1&branch_key=key_live_lmpPsfj2DP8CflI4rmzfiemerte7sgwm&callback=branch_callback__2:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
StravistiX.js:725 A previous sync exists on Sat Apr 28 2018 20:55:43 GMT+0200 (CEST)
ActivitiesSynchronizer.js:398 Fast sync mode enabled
ActivitiesSynchronizer.js:408 Local and remote activities count matches.
ActivitiesSynchronizer.js:418 Skipping HistoryChanges analisys
ActivitiesSynchronizer.js:450 Last sync date time saved:  Sat Apr 28 2018 20:58:43 GMT+0200 (CEST)
ActivitiesSynchronizer.js:460 Sync With Athlete Profile done
StravistiX.js:733 Fast sync finished Object
StravistiX.js:710 undefined
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
picture:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

**Comment by thomaschampagne** [comment]
Not a stravistix problem. Do you have an AD blocker?
