### ISSUE TITLE
Heatmap link broken?

### ISSUE THREAD

**Issue by cdanforth** [thomaschampagne/stravistix#587]
* Plugin version: _6.1.2__
  * Chrome/Opera/Chromium version: _65.0.3325.181____
  * OS version: _Mac OS 10.13.3____
  
In the last few days, the link to the Heat map doesn't work (gives a blank link).  I'm also running Stravini which 

Sorry if this isn't enough information.  I'm new to GitHub.

**Comment by thomaschampagne** [comment]
Heat map links works for me. You still have the problem? If not can you close the ticket? Ty

**Comment by cdanforth** [comment]
Looks okay now.  Not sure what was going on.  Thx.
