### ISSUE TITLE
Can't save the HR zones

### ISSUE THREAD

**Issue by K-brown** [thomaschampagne/stravistix#597]
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * Plugin version: _____
Plugin version: 6.2.1 Stable
Angular Core version: 5.2.10
Angular Material version: 5.2.5
D3js version: 4.13.0
  * Chrome version: _____
Version 66.0.3359.181 (Official Build) (64-bit)
  * OS version: _____
MAC OS X El Capitan
10.11.6
  
### Step 3: Describe the problem:
When I edit my HR zones and then click the save icon the response is QUOTA BYTES PER ITEM QUOTA EXCEEDED
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Actual Behavior:

  * What happened?
  * Do you have javascript errors logs in browser console?

  > Press F12 to see developer console and javascript logs

  ```javascript
  Copy and paste your console logs here.
  ```
  
#### Expected Behavior:

  * What did you expect to happen?
  
#### Media attachement:

>You can upload/attach any images to this ticket.

#### Providing your stravistix synced athlete activities can be usefull to solve the problem

> To export your activities click on "sync button" (top right and corner), then "Backup activities". You can zip the file and upload it here.

**Comment by thomaschampagne** [comment]
Hi. It's an issue i have to handle with chrome synced storage limitations. You should reduce numbers of zones you have on some sensors as workaround. Fix will come ;)
