### ISSUE TITLE
Show # Highlighted Stats under "Show extended statistics" button

### ISSUE THREAD

**Issue by KamensekD** [thomaschampagne/stravistix#61]
It would be great, if most important stats would be shown directly under the big orange "Show extended statistics" button in activity overview, so that you wouldn't have to click on it to see those important computed values.

I'd suggest to show the same values as shown in # Highlighted Stats, so:

for running: Move Ratio, 75% Quartile Speed (* better would be PACE), TRIMP, HRRAvg, 
for biking: Move Ratio, Toughness Factor, 75% Quartile Speed, TRIMP, HRRavg, Weighted Watts/kg
for other: TRIMP, HRRavg

**Comment by thomaschampagne** [comment]
Good idea !

**Comment by thomaschampagne** [comment]
This has been handled since https://github.com/thomaschampagne/stravistix/releases/tag/0.6.4

:)
