### ISSUE TITLE
Different RPM

### ISSUE THREAD

**Issue by mkonzen** [thomaschampagne/stravistix#616]
Hello, i'm starting to notice a difference between stravistix RPM (median cadence) and Strava.

https://www.strava.com/activities/1627603509/overview - Strava 85 and Stravistix 87
https://www.strava.com/activities/1623647772/overview - Strava 86 and Stravistix 88
https://www.strava.com/activities/1614623282/overview - Strava 85 and Stravistix 86
https://www.strava.com/activities/1608103684/overview - Strava 83 and Stravistix 85
https://www.strava.com/activities/1599728131/overview - Strava 81 and Stravistix 82

**Comment by akrzysztofek** [comment]
That's beacuse Strava displays average value (arithmetic mean) while Stravistix displays median.
