### ISSUE TITLE
SwimSS is calculated from elapsed time, not moving time.

### ISSUE THREAD

**Issue by donaldjohnston** [thomaschampagne/stravistix#620]
SwimSS seems to be calculated as a function of average pace and total elapsed time. This includes rest. It should be a function of average pace and moving time.

**Comment by thomaschampagne** [comment]
It's calculated from moving time (if swim watch can provide it) and elapsed time according the formula:

https://github.com/thomaschampagne/stravistix/blob/develop/plugin/app/src/app/fitness-trend/shared/services/fitness.service.ts#L224

**Comment by donaldjohnston** [comment]
Take this leisurely activity for example. Strava lists my moving time as 13:32, my elapsed time as 46:07, and my pace as 1:39/100m:

https://www.strava.com/activities/1690978527

Using the traditional method of calculating STSS, I should have a TSS of around 25, given my CSS. But, Stravistix returns a TSS of 85. I can get to that number by using my elapsed time instead of my moving time.
