### ISSUE TITLE
Corrected strava distance not taken into account on progressions

### ISSUE THREAD

**Issue by mikeyg123** [thomaschampagne/stravistix#622]
### Step 1: Are you in the right place?
yes
### Step 2: Describe your environment

Plugin version: 6.3.0 Stable
Angular Core version: 6.0.4
Angular Material version: 6.2.1
D3js version: 4.13.0

### Step 3: Describe the problem:

Year progressions / distance chart uses bad distance data even when the "correct distance" function has been used to make strava use gps data for distance 

#### Steps to reproduce:

Wahoo fitness cycling data with wheel speed sensor uploaded to strava
strava incorrectly interprets this data resulting in huge 30x distance shown
click "Distance(?)" and "Correct distance" on the strava activity view to make strava use gps data for distance
Strava now shows correct distance for activity
Go to stravastix year progressions distance page
see activity in chart with huge uncorrected distance
resync all activities
still see huge incorrect distance in chart

#### Actual Behavior:

see huge incorrect distance in chart 
  
#### Expected Behavior:

steps in year progressions distance chart would match distance strava shows for each activity
  
#### Media attachement:
![image](https://user-images.githubusercontent.com/20541399/41525849-453d1e78-72da-11e8-810f-3a58923fb9cf.png)

#### Providing your stravistix synced athlete activities can be usefull to solve the problem

[2018.6.18-9.27_v6.3.0.history.zip](https://github.com/thomaschampagne/stravistix/files/2110520/2018.6.18-9.27_v6.3.0.history.zip)

**Comment by thomaschampagne** [comment]
@mikeyg123 Thanks for report. What is the activity id which cause this big distance step?

**Comment by thomaschampagne** [comment]
Could you clear your synced activities and resync? Is your problem fixed in that case?

**Comment by mikeyg123** [comment]
Completely clearing and resyncing fixed it thanks.
So I guess there's something that isn't updated by the sync all

**Comment by mikeyg123** [comment]
activity https://www.strava.com/activities/1635390048
this one is particularly noticeable because the uncorrected distance is 149k vs 16k corrected.
