### ISSUE TITLE
Best Split

### ISSUE THREAD

**Issue by Frank-61** [thomaschampagne/stravistix#623]
did the best split feature disappear?
+ now there is best 20 minute speed where V¾ was more informative (for me): configurable?
(chrome/win10)

**Comment by thomaschampagne** [comment]
Best split feature is still there ;)

**Comment by Frank-61** [comment]
Yes , maybe it was a glicht of some component (might be human...on my side)The V75% is missed by me in the short statistics. Now best V 20 minutes. Utterly nice strava addon Thomas, I recommend it to all my friends.Thnx 4 the update.Frank

Verzonden via Yahoo Mail op Android 
 
  Op vr, aug. 10, 2018 om 14:38 schreef Thomas Champagne<notifications@github.com>:   
Best split feature is still there ;)
