### ISSUE TITLE
Running Functional Threshold Pace Setup

### ISSUE THREAD

**Issue by claudermilk** [thomaschampagne/stravistix#630]
It seems like in the new beta (6.4.0) from 2018/7/7 the conversion from metric to imperial got backwards. 

My slow pace of 5:30/km as a reference (entered as 330 sec) is now being converted to 3:25/mi. While that would be nice, it's not even close to reality! It should convert to about 8:52/mi.

**Comment by thomaschampagne** [comment]
Just restart browser to get 6.4.1 ;)
Or force update ;)

Le jeu. 12 juil. 2018 à 22:24, claudermilk <notifications@github.com> a
écrit :
