### ISSUE TITLE
Multiple Profiles

### ISSUE THREAD

**Issue by bizzehdee** [thomaschampagne/stravistix#637]
I have a chrome installation with 2 profiles on it. My own, and my wifes. If i sync stravistix under my profile, and then switch to my wifes profile, my information shows under her profile, and vica-verca.

Can stravistix be fixed to respect individual user profiles within chrome?

**Comment by thomaschampagne** [comment]
@bizzehdee As written in the FAQ you can do that in chrome directly: https://github.com/thomaschampagne/stravistix/wiki/Frequently-Asked-Questions#can-i-use-stravistix-extension-with-multiple-strava-accounts-in-the-same-browser

**Comment by bizzehdee** [comment]
It doesnt work. I have 2 chrome user profiles, completely separate. One strava account in one, and a different account in the other. And stravistix seems to ignore the profiles and share data between them.

**Comment by thomaschampagne** [comment]
Hmm it should. I'm using it everyday to separate my genuine strava data and my development strava data.

Do you have accounts represented like this?

![image](https://user-images.githubusercontent.com/151973/43489733-475b806c-951e-11e8-8d66-742c4be1b084.png)

**Comment by bizzehdee** [comment]
Yes, set up similar to yourself, my own profile and my wifes profile, each signed into our own strava account. If i switch to my own chrome profile, i see her data, so i nuke the data and resync, and see all my data. But then she will use her chrome profile, she will see my data rather than her own, and will have to do the same process
