### ISSUE TITLE
Strava Plus "drop down" can not open when on https://www.strava.com/pros

### ISSUE THREAD

**Issue by zob** [thomaschampagne/stravistix#76]
It seems the strava plus drop down menu is present also when on https://www.strava.com/pros
I don't know if strava plus is supposed to open on that page, however it does not "work" in the sense that the drop down doesn't unfold.
So recommended is either a fix or remove it from that page maybe?

It could be my system. I'm using google-chrome-stable 41.0.2272.118-1 on ubuntu 14.10, 64bit, kernel 3.16.0-34.

I just tested it with google-chrome-beta 42.0.2311.82-1, same system - this time all other extensions disabled. The issue is still present.

Thanks for ~~StravaPlus~~ stravistix.

**Comment by thomaschampagne** [comment]
@zob It's normal, i disabled it on pros page

Thanks

Tom
