### ISSUE TITLE
Custom Splits

### ISSUE THREAD

**Issue by aravindajju** [thomaschampagne/stravistix#77]
Strava doesn't have the ability see pace by custom splits.   To be fair, none of the software (garmin, endomondo, runkeeper etc.,) I use has this feature.  If I run intervals of varying lengths 200m,400m,800m etc., with different rest periods, there is no means to see the pace by splits matching my intervals.  This would be a great addition to Stravaplus.   

Great work on the plugin.   Keep it up.

**Comment by thomaschampagne** [comment]
This feature (#70) is in 0.6.0 milestone not released yet. You can checkout 0.6.0-rc1 tag for testing: https://github.com/thomaschampagne/StravaPlus/releases/tag/0.6.0-rc1
