### ISSUE TITLE
"export effort as virtual partner" went all crazy

### ISSUE THREAD

**Issue by tedder** [thomaschampagne/stravistix#82]
I assume related to the #79 effort. I don't know why but it appears to be a little imperfect. Note the duplication.
![screen shot 2015-05-02 at 3 29 12 pm](https://cloud.githubusercontent.com/assets/97914/7443004/0c4c6d28-f0e0-11e4-970e-096d2202a558.png)

**Comment by thomaschampagne** [comment]
Hi, do you have activity example?

**Comment by tedder** [comment]
Yeah- it's on this: https://www.strava.com/activities/296896645/

Does that help? Let me know if you need anything else. I'm on OSX, Chrome 43 (beta).

**Comment by thomaschampagne** [comment]
Thanks Tedder. 

Do you have the full URL to the segement ? eg https://www.strava.com/activities/296896645/segments/6980458681 ?

Do you reproduce the problem each time or some time? or just 1 time?

Thanks ;)

Tom

**Comment by thomaschampagne** [comment]
I found it @ https://www.strava.com/activities/296896645/segments/6980458954

I'm not able to get the glich :s

**Comment by tedder** [comment]
I clicked on about a half-dozen segments, they all have the glitch (usually with three "Export effort" lines, not many as above).

Totally could be the Chrome Beta, not all versions of Chrome. Let me know if I can help with anything else. I'm attaching the source/DOM for one of them.

![screen shot 2015-05-02 at 3 51 08 pm](https://cloud.githubusercontent.com/assets/97914/7443036/1fe0fa68-f0e3-11e4-98cc-949321d56672.png)

**Comment by thomaschampagne** [comment]
Thanks tedder.

Ok for chrome 43 beta. I will try on another workstation. I have stable chrome on mine

Beside I tried with latest version of chromium 44.0.2390.0. It's a standalone package. I'm not getting your bug

https://download-chromium.appspot.com/?platform=Mac

Thanks again for reporting me this problem ;)

Thomas

**Comment by tedder** [comment]
Interesting- I grabbed that version of Chromium, loaded Strava, then grabbed stravistix. I get the same duplication in Chromium.

Going with the theory that it may be the Retina display of my computer, I grabbed a nearby Air, which has Chrome 42, installed Stravistix, then opened a segment. It doesn't have duplication. I then used the Chromium 44 download, installed Stravistix, opened a segment. Again, no duplication.

That somewhat supports the Retina theory.

**Comment by thomaschampagne** [comment]
Strange :s.
I was able to reproduce this 1 time on linux mint and mobile device emulation.

![screenshot from 2015-05-04 09 12 30](https://cloud.githubusercontent.com/assets/151973/7449818/c534b238-f23d-11e4-82b0-9d0ca907b4e4.png)

Lookng at this. Thanks again

**Comment by ireun** [comment]
I can confirm this, it's not happening every time, but it's happening. I'm using chrome  42.0.2311.152

**Comment by thomaschampagne** [comment]
i which version did you gte the problem? A made a fix into 0.6.3

Thanks

Tom

**Comment by ireun** [comment]
Well, it might be the previous version, sorry, haven't looked at how old this issue is. After some cliicking i can say this is fixed, you can close this one. :)

**Comment by thomaschampagne** [comment]
no problem i will wait a little by the way before closing to make sure. If it happend on your computer ;)

Tom

**Comment by ireun** [comment]
And.. It;s not fixed. http://www.strava.com/activities/307103352/segments/7239701251

![2015-05-18_20-17-59](https://cloud.githubusercontent.com/assets/695818/7687095/09167e38-fd9b-11e4-9eae-0a826440ff4f.png)

**Comment by thomaschampagne** [comment]
:( 
It's better... 2 duplicated buttons instead of 3 :)

So I keep it open :(

Maybe any idea of fix? Commits history about this is here: #79 

Thanks

Tom

**Comment by tedder** [comment]
I'm loath to debug stripped javascript, but my assumption is that VirtualPartnerModifier is getting called multiple times per data element. Since it isn't called many times on the same visible page, it's probably possible to put a breakpoint on it, yeah? Or at least console.log it and release it with the log enabled?

**Comment by thomaschampagne** [comment]
Already deleaded with breakpoints and console.log :) The main problem is that the bug isn't reproductible every time :)

**Comment by spargher** [comment]
It seems to me that every time i change the ranking type (overall, this year, men, ecc...) I get a new duplicate button, so if I can get  a lot of buttons... Hope this helps
![immagine](https://cloud.githubusercontent.com/assets/12657340/7879865/8ca1fbfe-05f4-11e5-8365-6704cf42ef02.jpg)

**Comment by thomaschampagne** [comment]
Indeed ! Thanks for this analisys.
