### ISSUE TITLE
Best 60 & 120 seconds HRR (Heart Recovery Rate) for each ride

### ISSUE THREAD

**Issue by thomaschampagne** [thomaschampagne/stravistix#90]
http://www.enhancedmedicalcare.com/2013/01/20/improve-heart-health-by-knowing-your-recovery-heart-rate/
http://www.livestrong.com/article/260805-the-recovery-heart-rate-time-after-cardio-exercise/

**Comment by glandais** [comment]
Done with commits on best drop/rise in best splits
