### ISSUE TITLE
Don't open random tabs

### ISSUE THREAD

**Issue by rubenv** [thomaschampagne/stravistix#91]
Please don't open random tabs when you push an update. That's very spammy.

**Comment by rubenv** [comment]
Aside from that: nothing but love for Stravistix!

**Comment by thomaschampagne** [comment]
Thanks man

It's not random tab :), It's fresh stravistix main website :) 

This tab will no longer be displayed on coming up updates by the way. Just to inform existence to users

Cheers,

Tom

**Comment by math2k** [comment]
+1, the javascript alert is also completely unnecessary and disruptive.

But thanks for your work!

**Comment by thomaschampagne** [comment]
You were right. Listen to users. Not listen to me...

Hotfix done. 0.7.1 published.

Thanks

Tom
