### ISSUE TITLE
export effort as virtual partner 

### ISSUE THREAD

**Issue by tulsadome** [thomaschampagne/stravistix#92]
for this activity http://www.strava.com/activities/302031694/segments/7109042885
when I first click export i get a white page with the error 

{"error":"invalid effort id"}

i then have to click analyze and from the analyze screen click on the segment title to return back to the first page with export effort as virtual partner. at that point export as is doubled up so there are two. if i click either of them it will save the effort.

**Comment by thomaschampagne** [comment]
I'm not able to reproduce your problem :s
