### ISSUE TITLE
Weather show actual status, not a weather at ride date

### ISSUE THREAD

**Issue by rostykk** [thomaschampagne/stravistix#93]

**Comment by thomaschampagne** [comment]
Hi rostykk thanks for report

Do you have activity example?

Strange I'm giving the start date of act to windytv while embeding the weather.

Tom

**Comment by rostykk** [comment]
example:
http://rostyk.net/test/stravix_weather.png

activities in february year ago: https://www.strava.com/activities/110729832 
and recent: https://www.strava.com/activities/310770887
shows exactly the same data

**Comment by rostykk** [comment]
So iframe links looks like
https://embed.windyty.com/?surface,wind,2014-02-02,52.24642075,4.5682495,20,,,,
and
https://embed.windyty.com/?surface,wind,2015-05-24,52.257484749999996,4.5575865,20,,,,

**Comment by rostykk** [comment]
Sorry for mine not programmings skills.
What i notice:
for example same activity: https://www.strava.com/activities/310770887
it says:
*startDateLocal: 1432473090*

so you function in **stravistix/hook/extension/js/modifiers/WindyTyModifier.js**

var date = new Date(pageView.activity().get('startDateLocal') * 1000); // will give date=1432473090000

and after:
date.toISOString().split('T')[0] give result "2015-05-24" not like inspected for windity yyyy-mm-dd**-hh**

and also windyty had only 00:00 / 06:00 / 12: 00 and 18:00 time slots
So probably you should roundUp  for to this values (or use by default "12")

**Comment by thomaschampagne** [comment]
Don't  worry add hour  is easilly fixable. With the  right and with good
hour ;) fixed  in  0.7.2

Tom

**Comment by rostykk** [comment]
Cool. Thanks!

**Comment by thomaschampagne** [comment]
__Dev notes__

Fix bug with this simple computation:
```
var windyTyHour = Math.round(activityHour/6) * 6;
```
Should return the nearest windyty hour **(0, 6, 12 or 18)** for a given activity hour **(0h to 23h)**

**Comment by Filliny** [comment]
Windity claims low space - no hostorical data then - need another service implementation... 
https://community.windytv.com/topic/3487/no-more-historical-data-on-windytv-maybe-in-4q-2017

**Comment by thomaschampagne** [comment]
indeed. Do you know another one?

**Comment by rostykk** [comment]
No free solution out of the box, as before.
Historical data without map
A time-machine request returns the observed weather at a given time (for many places, up to 60 years in the past):
https://api.darksky.net/forecast/[key]/[latitude],[longitude],[time]

https://darksky.net/dev/docs/time-machine

- First **thousand** API calls you make every day are free
- Every API call after that costs $0.0001 each
- Credit needed: Credit us with a “Powered by Forecast”
