### ISSUE TITLE
Provide 'Stride length' graphs for running

### ISSUE THREAD

**Issue by philipwhiuk** [thomaschampagne/stravistix#94]
With running you can calculate stride length if you have cadence and distance (from an independent source). Garmin Connect gives you the run's average stride length. But the data is available to graph it.

Also I note that the cadence for this run: https://www.strava.com/activities/317005236/overview is given in the graph as 170-171. But the Strava graph gives 80-81 (which should be 160 when you account for both feet). What's going on here?

**Comment by thomaschampagne** [comment]
I'm not sure to understand the problem.

Do you activated this in options?

![capture](https://cloud.githubusercontent.com/assets/151973/7966462/7ff277ba-0a24-11e5-9c0a-a6bcf91c6aa3.PNG)

Getting 85.0 to 85.5	spm for this ACT. Table in graph included

Tom

**Comment by philipwhiuk** [comment]
Yes, I did have that option selected. The problem was/is that the first zone (which the default config is 85.0->85.5 / 170->17.1) actually contains stuff below that zone as well as stuff in the zone. And all my data was below the first zone. I adjusted the zones somewhat and now it looks as expected.

I think the only question I would have is if the running defaults are good defaults.

In terms of stride length datavis, I might work on it myself and submit a pull request :)

**Comment by thomaschampagne** [comment]
Defaults seems to be good?
```json
 runningCadence: [{
            from: 85,
            to: 85.5
        }, {
            from: 85.5,
            to: 86
        }, {
            from: 86,
            to: 86.5
        }, {
            from: 86.5,
            to: 87
        }, {
            from: 87,
            to: 87.5
        }, {
            from: 87.5,
            to: 88
        }, {
            from: 88,
            to: 88.5
        }, {
            from: 88.5,
            to: 89
        }, {
            from: 89,
            to: 89.5
        }, {
            from: 89.5,
            to: 90
        }, {
            from: 90,
            to: 90.5
        }, {
            from: 90.5,
            to: 91
        }, {
            from: 91,
            to: 91.5
        }, {
            from: 91.5,
            to: 92
        }, {
            from: 92,
            to: 92.5
        }, {
            from: 92.5,
            to: 93
        }, {
            from: 93,
            to: 93.5
        }, {
            from: 93.5,
            to: 94
        }]
```
