### ISSUE TITLE
Autoscroll prevents clicking on links in footer in feed view

### ISSUE THREAD

**Issue by benze** [thomaschampagne/stravistix#95]
I love the feed autoscrolling, but it prevents me from clicking on any of the links in the footer.
Workaround is to disable the autoscroll, or open another page (non-feed) to access the links. 

I don't know if there is a way to prevent this but thought I would mention the issue I just encountered.

**Comment by thomaschampagne** [comment]
You can disable this feature here:

chrome-extension://dhiaggccakkgdfcadnklkbljcgicpckn/options/app/index.html#/commonSettings

I can't manage auto/stop scroll together

Tom
