### ISSUE TITLE
¿languages?

### ISSUE THREAD

**Issue by 1000io** [thomaschampagne/stravistix#99]
Are you planing to create a "dictionary file" to translate all the aplication and the help?
Thanks!

**Comment by thomaschampagne** [comment]
Yes. But need help for this. 

Any help for change code structure?

Tom

**Comment by praveentiru** [comment]
@thomaschampagne Close this issue as it is duplicate of #10

**Comment by thomaschampagne** [comment]
closed because of duplicate of #10
